/* ============================================================================
   ENGLISH TRANSLATIONS
   ui   → chaînes d'interface (clé = texte français)
   nodes → contenu des nœuds de l'arbre de diagnostic
   ========================================================================== */
export const EN = {

  /* ---- Chaînes d'interface ---- */
  ui: {
    // Splash
    'Démarrer un diagnostic': 'Start a diagnostic',
    'Diagnostic pas à pas': 'Step-by-step diagnostic',
    'Guide de diagnostic pas à pas pour techniciens et clients':
      'Step-by-step diagnostic guide for technicians and customers',
    'v0.2 · usage interne Logimatiq': 'v0.2 · Logimatiq internal use',

    // Login
    'Connexion': 'Login',
    'Identifiants fournis par Logimatiq': 'Credentials provided by Logimatiq',
    'Identifiant': 'Username',
    'Votre login': 'Your username',
    'Mot de passe': 'Password',
    'Votre mot de passe': 'Your password',
    'Identifiant ou mot de passe incorrect.': 'Incorrect username or password.',
    'Se connecter →': 'Sign in →',
    'Contactez Logimatiq pour obtenir vos identifiants':
      'Contact Logimatiq to get your credentials',

    // Home
    'Connectez-vous': 'Sign in',
    'Chercher un symptôme, une fiche…': 'Search for a symptom, a guide…',
    'Démarrer un diagnostic': 'Start a diagnostic',
    'Bientôt disponible': 'Coming soon',
    'Guide de mise en service': 'Installation guide',
    'Checklist installation EPIMAT': 'EPIMAT installation checklist',
    'Récents': 'Recent',
    'Aucun diagnostic récent': 'No recent diagnostics',
    'Les diagnostics terminés apparaîtront ici':
      'Completed diagnostics will appear here',

    // Bottom nav
    'Accueil': 'Home',
    'Fiches': 'Guides',
    'Historique': 'History',

    // Symptoms
    'Trappe': 'Hatch',
    'Tambour': 'Drum',
    'Alimentation': 'Power',
    'Quel est le problème ?': 'What is the problem?',
    'Affichage': 'Display',
    'Réseau': 'Network',
    'Badge': 'Badge',
    'Logiciel': 'Software',
    'Config': 'Config',

    // Machine select
    'Quelle machine ?': 'Which machine?',
    'Machines enregistrées': 'Registered machines',
    'Nouvelle machine': 'New machine',
    '← Retour à la liste': '← Back to list',
    'Numéro de série *': 'Serial number *',
    'Ex : EPM-2024-0042': 'E.g.: EPM-2024-0042',
    'Site / Emplacement': 'Site / Location',
    'Ex : Entrepôt Paris, Rayon 3…': 'E.g.: Paris Warehouse, Row 3…',
    'Client / Société': 'Customer / Company',
    'Nom du client final': 'End customer name',
    'Le numéro de série est obligatoire.': 'Serial number is required.',
    'Veuillez remplir tous les champs obligatoires.': 'Please fill in all required fields.',
    'Enregistrer et continuer →': 'Save and continue →',

    // Diag UI
    'Étape': 'Step',
    'étapes': 'steps',
    'Procédure faite': 'Done',
    'Question': 'Question',
    'Procédure': 'Procedure',
    '← Retour': '← Back',
    "C'est fait ✓": 'Done ✓',
    'Quitter': 'Quit',
    'Quitter ce diagnostic ?': 'Quit this diagnostic?',
    'Se déconnecter ?': 'Sign out?',
    'Cheminement du diagnostic': 'Diagnostic path',
    'Copier le rapport': 'Copy report',
    '✓ Copié !': '✓ Copied!',
    'Contacter le SAV Logimatiq': 'Contact Logimatiq Support',
    'Refaire ce diagnostic': 'Redo this diagnostic',
    'Terminer': 'Done',
    'Nœud introuvable.': 'Node not found.',
    'SAV': 'Support',

    // Rapport
    'RAPPORT DIAGNOSTIC LOGIMATIQ': 'LOGIMATIQ DIAGNOSTIC REPORT',
    'N° série :': 'Serial no:',
    'Site     :': 'Site     :',
    'Conclusion :': 'Conclusion:',
    'Machine  :': 'Machine  :',
    'Problème :': 'Problem  :',
    'Date     :': 'Date     :',
    'Généré par Logimatiq SAV App': 'Generated by Logimatiq Support App',
    'Rapport diagnostic Logimatiq': 'Logimatiq Diagnostic Report',

    // Outcome pills
    'Résolu': 'Resolved',
    'Pièce': 'Part',

    // History
    'Aucun diagnostic terminé': 'No completed diagnostics',
    'Les diagnostics complétés apparaîtront ici':
      'Completed diagnostics will appear here',
    'Total': 'Total',
    'Résolus': 'Resolved',
    'Taux': 'Rate',

    // Stats
    'Aucune donnée disponible': 'No data available',
    'Effectuez des diagnostics pour voir les statistiques':
      'Run diagnostics to see statistics',
    'Diagnostics': 'Diagnostics',
    'Machines': 'Machines',
    'Répartition des résultats': 'Result breakdown',
    'SAV requis': 'Support needed',
    'Pièce à changer': 'Part to replace',
    'Machines les plus actives': 'Most active machines',
    'Sociétés les plus actives': 'Most active companies',
    'Pannes les plus fréquentes': 'Most common faults',

    // Setup
    'Mise en service': 'Installation',
    'Base de connaissances': 'Knowledge base',
    'Progression': 'Progress',
    '✓ Complété': '✓ Completed',
    '✓ Installation complète !': '✓ Installation complete!',
    'La machine est prête à l\'utilisation.': 'The machine is ready to use.',
    'Réinitialiser la checklist': 'Reset checklist',
    'Réinitialiser toute la checklist d\'installation ?': 'Reset the entire installation checklist?',

    // Faults
    'Pannes': 'Faults',
    'Tambour, trappe, moteur…': 'Drum, hatch, motor…',
    'Pannes récurrentes': 'Recurring faults',
    'Logiciel EPIMAT': 'EPIMAT software',
    'Rechercher une panne…': 'Search for a fault…',
    'Tout': 'All',
    'Symptômes': 'Symptoms',
    'Étapes de résolution': 'Resolution steps',
    'Photo à venir': 'Photo coming soon',
    'Lancer le diagnostic': 'Start the diagnostic',
    'Appeler le SAV Logimatiq': 'Call Logimatiq Support',
    'Aucune panne trouvée': 'No fault found',
    'Essayez un autre mot-clé': 'Try another keyword',
    'Critique': 'Critical',
    'Urgent': 'Urgent',
    'Courant': 'Common',

    // KB
    'Fiches PDF': 'PDF Guides',
    "Fiches d'intervention": 'Repair sheets',
    "Voir la fiche d'intervention": 'See the repair sheet',
    'Documents': 'Documents',
    'Non renseigné': 'Not specified',
    'Toutes les fiches': 'All sheets',
    'Avant de commencer': 'Before you start',
    'Contrôle final': 'Final check',
    'À valider avec Logimatiq': 'To confirm with Logimatiq',
    'Codes erreur': 'Error codes',
    'écran noir, modem, badge…': 'black screen, modem, badge…',
    'ERR_SYNC, badge, réseau…': 'ERR_SYNC, badge, network…',
    'Aucun résultat pour': 'No results for',

    // User roles
    'Client': 'Customer',
    'Technicien revendeur': 'Reseller technician',
    'Technicien Logimatiq': 'Logimatiq technician',

    // Toolbar / headers statiques HTML
    'Statistiques': 'Statistics',
    'Se déconnecter': 'Sign out',
    'Logimatiq SAV': 'Logimatiq Support',
    'Tableau de bord': 'Dashboard',
    'EPIMAT': 'EPIMAT',
  },

  /* ---- Titres des symptômes (tree.js symptoms[]) ---- */
  symptoms: {
    't.epimat.trappe': 'Hatch stuck / "Problème de distribution" (dispensing problem) / empty compartment',
    't.epimat.tambour': '"EN PANNE" (out of order) / drum stuck or wrongly positioned',
    't.epimat.alim': 'Machine powered off / no power',
    't.epimat.screen':   'Black screen / no image / frozen screen',
    't.epimat.internet': 'No internet connection / modem offline',
    't.epimat.badge':    'Badge not read / not recognized / wrong number',
    't.log.demarrage':   "Software won't start / crashes",
    't.log.synchro':     'Software synchronization error',
    't.log.impression':  'Printing problem',
    't.log.config':      'Configuration / initial setup',
    't.vet.ph':          'To complete',
  },

  /* ---- Nœuds de l'arbre de diagnostic ---- */
  nodes: {

    /* === ARBRE ÉCRAN === */
    s_debut: {
      title: 'Is the machine plugged into the power outlet?',
      help: "Check that the machine's power cable is properly plugged into the room's wall outlet.",
      answers: ['Yes, plugged in', 'No, unplugged'],
    },
    s_brancher: {
      title: 'Connect the machine to the power outlet',
      steps: [
        'Firmly connect the power cable on the machine side (supplied cable, exits at the bottom)',
        "Plug the other end into the room's wall outlet",
        'Wait 10 seconds',
      ],
    },
    s_led_ecran: {
      title: 'What is the color of the screen LED indicator?',
      help: 'The "Power Led" indicator on the back of the screen, above the adjustment buttons (see the photos).',
      answers: ['Red', 'Off (no LED)', 'Green (image visible, other problem)'],
      media: [
        'Indicator off',
        'Indicator red',
        'Indicator green',
      ],
    },
    s_rouge_pc_led: {
      title: 'Is the PC LED on?',
      help: 'Light indicator on the front of the PC case built into the machine.',
      answers: ['Yes, PC LED on', 'No, PC off'],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    s_rouge_pc_ventilo: {
      title: 'Check the PC power supply',
      steps: [
        'Listen or look whether the PC fan is running',
        'Go to the back of the PC case',
        'Locate the ON/OFF switch near the PC power socket',
        'Switch it to OFF, wait 5 seconds, then switch it back to ON',
        'Return to the front and press the PC Power button',
        'Wait 15 seconds',
      ],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    s_rouge_pc_demarre: {
      title: 'Did the PC start? (LED on)',
      answers: ['Yes, LED on', 'No, still off'],
    },
    s_rouge_multiprise: {
      title: 'Is the red LED on the internal power strip lit?',
      help: 'White power strip on the electrical panel plate, inside the machine (open the front, slide the plate forward). The PC is plugged into it: if it is off, the fault is in the power supply, not in the PC.',
      answers: ['Yes, red LED lit', 'No, power strip off'],
      media: 'Electrical panel plate: the internal power strip (white) is in the middle, below the EPI RT board',
    },
    s_rouge_rebrancher_vga: {
      title: 'Disconnect and reconnect the VGA cable',
      help: "The screen's 3 cables (USB, power, VGA) all connect at the same place behind the screen.",
      steps: [
        'Locate the VGA cable (blue screw connector) between screen and PC',
        'Unplug the cable on the screen side, then on the PC side',
        'Firmly reconnect on both sides and tighten the thumbscrews',
        'Wait 10 seconds',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_rouge_vga_result: {
      title: 'Has the image returned on the screen?',
      answers: ['Yes, image OK', 'No, still red'],
    },
    s_rouge_changer_vga: {
      title: 'Replace the VGA cable',
      steps: [
        'Unplug the old VGA cable from both sides',
        'Connect a new VGA cable on the PC side, then on the screen side',
        'Tighten the thumbscrews',
        'Wait for the image to return (10 seconds)',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_rouge_apres_changer_vga: {
      title: 'Is the image now visible?',
      answers: ['Yes, image OK', 'No, screen red'],
    },
    s_rouge_pc_verif: {
      title: 'Is the PC really on and running?',
      help: 'PC LED lit and fan running. Often the PC has turned off or no longer works.',
      answers: ['Yes, the PC is running', "No, or I don't know"],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    s_rouge_pc_relancer: {
      title: 'Restart the PC',
      steps: [
        'Go to the back of the PC case',
        'Switch the ON/OFF switch to OFF, wait 5 seconds, then switch it back to ON',
        'Return to the front and press the PC Power button',
        'Wait 15 seconds',
      ],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    s_rouge_pc_relancer_result: {
      title: 'What happens?',
      answers: ['The image is back', 'The PC started, but still no image', 'The PC stays off'],
    },
    s_eteint_machine: {
      title: 'Is the rest of the machine powered on?',
      help: 'PC LED, badge reader indicator, modem indicators.',
      answers: ['No, everything seems off', 'Yes, only the screen is off'],
    },
    s_eteint_cable: {
      title: 'Is the power cable properly connected on the screen side and on the power supply side?',
      help: 'It arrives behind the screen together with the USB and VGA cables.',
      answers: ['Yes, connected', 'No, disconnected'],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_eteint_brancher_cable: {
      title: 'Connect the screen power cable',
      steps: [
        'Firmly connect the end on the screen side',
        'Check the connection on the power supply side and on the power strip side',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_eteint_cable_result: {
      title: 'Does the screen turn on?',
      answers: ['Yes', 'No'],
    },
    s_eteint_multiprise: {
      title: 'Is the red LED on the internal power strip lit?',
      help: 'White power strip on the electrical panel plate, inside the machine (open the front, slide the plate forward). Its red indicator lit = it is powered.',
      answers: ['Yes, red LED lit', 'No, power strip off'],
      media: 'Electrical panel plate: the internal power strip (white) is in the middle, below the EPI RT board',
    },
    s_eteint_changer_alim: {
      title: 'Replace the screen power supply',
      steps: [
        'Locate the screen power supply (black box on the cable)',
        'Unplug the faulty power supply',
        'Connect a new power supply of the same reference',
        'Turn the screen back on',
      ],
    },
    s_eteint_alim_result: {
      title: 'Did the screen turn on?',
      answers: ['Yes, screen on', 'No, still off'],
    },
    s_vert_symptome: {
      title: 'What is the problem?',
      answers: [
        'The touchscreen does not respond',
        'Damaged image: flickering, colors, broken screen',
        'DistEPI is not displayed (Windows desktop visible)',
        'Screen frozen / stuck',
        'Windows or BIOS error message',
      ],
    },
    s_vert_image: {
      title: 'What do you see on the screen?',
      answers: [
        'Flickering or abnormal colors',
        'Wrong resolution (image too large or cut off)',
        'Broken or cracked screen',
      ],
    },
    s_vert_vga: {
      title: 'Check the VGA cable',
      steps: [
        'Locate the VGA cable (blue connector) between screen and PC',
        'Unplug and firmly reconnect on both sides',
        'Tighten the thumbscrews',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_vert_vga_result: {
      title: 'Has the image problem disappeared?',
      answers: ['Yes, stable image', 'No, problem persists'],
    },
    s_vert_usb: {
      title: 'Check the USB cable between screen and PC',
      steps: [
        'Locate the USB cable connecting the screen to the PC (needed for touch)',
        'Unplug and firmly reconnect on both sides',
        'If possible, try another USB port on the PC',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_vert_usb_result: {
      title: 'Is the touchscreen responding now?',
      answers: ['Yes, touch OK', 'No, still inactive'],
    },
    s_vert_distepi: {
      title: 'Launch the DistEPI software',
      steps: [
        'On the Windows desktop, double-click the DistEPI icon',
        'If the icon is missing: run C:\\EPI\\DistEPI.exe',
        'Wait for full loading (about 30 seconds)',
      ],
    },
    s_vert_distepi_result: {
      title: 'Did DistEPI launch correctly?',
      answers: ['Yes, DistEPI launched', "No, won't open"],
    },
    s_vert_resolution: {
      title: 'Correct the screen resolution',
      steps: [
        'Right-click on the Windows desktop',
        'Click "Display settings"',
        'Under Resolution, choose 1280 × 720 for a 17-inch screen, 800 × 600 for an 8-inch screen',
        'Click "Keep changes"',
      ],
    },
    s_vert_resolution_result: {
      title: 'Is the resolution correct now?',
      answers: ['Yes, display correct', 'No, still incorrect'],
    },
    s_redemarrer_distrib: {
      title: 'Restart the dispenser',
      steps: [
        'Start → Shut down → Restart',
        'If the screen is frozen: hold the PC Power button for 5 seconds, then turn it back on',
        'Wait for Windows and DistEPI to fully start',
      ],
    },
    s_redemarrer_distrib_result: {
      title: 'After the restart, is DistEPI displayed correctly?',
      answers: ['Yes', 'No'],
    },
    s_vert_redemarrer: {
      title: 'Restart the machine',
      steps: [
        'Click Start → Shut down → Restart',
        'If screen is frozen: hold the Power button for 5 seconds to force shutdown',
        'Turn back on with the Power button',
        'Wait for Windows to fully restart',
        'Check that DistEPI restarts automatically',
      ],
    },
    s_vert_redemarrer_result: {
      title: 'Is the machine working correctly after restart?',
      answers: ['Yes, everything OK', 'No, problem persists'],
    },
    s_vert_erreur: {
      title: 'Note the message, then restart the dispenser',
      steps: [
        'Photograph or write down the error message',
        'Start → Shut down → Restart (or hold the Power button for 5 seconds)',
        'Wait for the full startup',
      ],
    },
    s_vert_erreur_result: {
      title: 'Has the error message disappeared?',
      answers: ['Yes', 'No, it comes back'],
    },

    /* === ARBRE INTERNET === */
    i_debut: {
      title: 'What is the problem?',
      help: 'Four-Faith modem indicators: steady blue Online = internet OK; blinking ETH = link with the PC OK.',
      answers: [
        '"Online" LED off',
        '"Online" LED on but DistEPI sync error',
        'Frequent disconnections / unstable signal',
      ],
      media: [
        'Location of the modem in the machine (circled in red)',
        'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
      ],
    },
    i_pwr_led: {
      title: "Is the modem's PWR LED on (steady blue)?",
      answers: ['Yes', 'No, modem off'],
      media: 'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
    },
    i_alim_modem: {
      title: "Check the modem's power supply",
      steps: [
        'Check that the power jack is fully inserted into the modem',
        'Check that its power adapter is plugged in and powered',
        'Wait 2 to 3 minutes',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_alim_modem_result: {
      title: 'Does the PWR LED turn on?',
      answers: ['Yes', 'No'],
    },
    i_reboot_modem: {
      title: 'Restart the modem',
      steps: [
        "Unplug the modem's power supply (jack): it has no switch",
        'Wait 30 seconds',
        'Plug the power supply back in',
        'Wait 2 to 3 minutes for the modem to reconnect to the mobile network',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_reboot_result: {
      title: 'Is the "Online" LED now on?',
      answers: ['Yes, blue LED on', 'No, still off'],
    },
    i_antennes_check: {
      title: 'Check the 2 modem antennas',
      steps: [
        'Check that both antennas are properly screwed onto the modem',
        'If an antenna is loose, screw it back firmly',
        'Wait 1 minute and observe the Online LED',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_antennes_result: {
      title: 'Did the "Online" LED turn on?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    i_sim_led: {
      title: 'Is the modem SIM LED on?',
      help: 'Blue SIM LED = SIM card detected.',
      answers: ['Yes, SIM LED on', 'No, SIM LED off'],
      media: 'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
    },
    i_reinsertion_sim: {
      title: 'Re-insert the SIM card',
      steps: [
        "Cut the modem's power supply",
        'Eject the SIM with a pen or a pointed tool (ejection hole)',
        'Clean the gold contacts with a dry cloth',
        'Re-insert the SIM the right way round, then turn the modem back on',
        'Wait 2 to 3 minutes',
      ],
      media: 'Eject the SIM with a pointed tool in the ejection hole',
    },
    i_sim_result: {
      title: 'Is the SIM LED now on?',
      answers: ['Yes, SIM LED on', 'No, still off'],
    },
    i_lire_apn: {
      title: "Note the modem's current APN",
      help: 'The modem answers even without internet: you just need to be at the machine.',
      steps: [
        "On the machine's PC, open a browser and go to 192.168.1.1",
        "Log in with the modem's credentials (Logimatiq SIM procedure)",
        'Setup menu: write down the APN shown',
      ],
      media: 'Modem interface (192.168.1.1): Setup menu, APN field',
    },
    i_setup_grizzly: {
      title: 'Run the router configuration again (Logimatiq program)',
      steps: [
        'Run setup_config_routeur_four_faith_1.0.0.17.exe (C:\\EPI folder)',
        'User Account Control: "Oui" (Yes), then "Suivant" (Next), "Suivant", "Installer" (Install)',
        '"La connexion à Internet est-elle fournie par un routeur installé par Logimatiq ?" (internet provided by a Logimatiq router?): "Oui" (Yes)',
        'Choose the APN from the list (wbdata, matooma.m2m, orange…): the same one you noted if the SIM card has not changed; with a new SIM, ask Support for its APN; then "Enregistrer les paramètres et Fermer" (Save settings and Close)',
        '"Configuration terminée avec succès" (configuration completed): OK, then "Non, je préfère redémarrer plus tard" (restart later) and "Terminer" (Finish)',
        'Wait 2 to 3 minutes and observe the Online LED',
      ],
      media: [
        'Question "La connexion à Internet est-elle fournie par un routeur installé par Logimatiq ?": answer "Oui" (Yes)',
        'Choose the SIM card APN from the list',
      ],
    },
    i_setup_result: {
      title: 'Is the "Online" LED now on?',
      answers: ['Yes, blue LED on', 'No, still off'],
    },
    i_eth_led: {
      title: "Is the modem's ETH LED blinking?",
      help: "Blinking ETH = the modem is exchanging data with the machine's PC.",
      answers: ['Yes, it is blinking', 'No, off or steady'],
      media: 'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
    },
    i_connexion_distante: {
      title: "Can we connect remotely to the machine's PC?",
      help: 'Only if you have your own remote access software installed on this PC (a reseller, for example). If remote access works, the RJ45 cable is not the cause.',
      answers: [
        'Yes, remote connection OK',
        'No, no remote connection',
        'No remote access software',
      ],
    },
    i_test_url: {
      title: 'Test access to the EPIMAT server from the PC',
      steps: [
        "On the machine's PC, open any web browser",
        'Go to https://epimat.logimatiq.com',
        'Check that the page opens without a certificate warning',
      ],
    },
    i_test_url_result: {
      title: 'Does the page open normally?',
      help: 'If the browser can reach the EPIMAT address, the EPIMAT applications work (network prerequisites).',
      answers: ['Yes', 'No'],
    },
    i_rj45_check: {
      title: 'Check the RJ45 cable (PC ↔ modem)',
      steps: [
        "Locate the RJ45 cable connecting the PC to the modem's ETH port",
        'Unplug and reconnect firmly on both ends until it clicks',
        'Check that the Windows PC shows an internet connection',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_rj45_result: {
      title: 'Does the Windows PC now have internet access?',
      answers: ['Yes, internet OK', 'No, still no network'],
    },
    i_clientsynch: {
      title: 'Test with ClientSynch DB EPI (Grizzly)',
      steps: [
        'On the Windows desktop, open the ClientSynch DB EPI software',
        'Run the data receive and send test',
        'Observe whether the test passes or fails',
      ],
      media: 'ClientSynch DB EPI: procedure (photos coming soon)',
    },
    i_clientsynch_result: {
      title: 'Did the ClientSynch test succeed?',
      answers: ['Yes, test OK', 'No, test fails'],
    },
    i_reboot_pc_distepi: {
      title: 'Restart the PC',
      steps: [
        'Click Start → Shut down → Restart',
        'Wait for Windows to fully restart',
        'Check that DistEPI restarts and sync works',
      ],
    },
    i_reboot_distepi_result: {
      title: 'Is DistEPI working correctly after the restart?',
      answers: ['Yes, sync OK', 'No, error persists'],
    },
    i_signal_faible: {
      title: 'Check antennas and reposition the modem',
      help: 'Signal LEDs (bars in the middle of the modem): the more bars, the better the signal.',
      steps: [
        'Check that both antennas are properly screwed onto the modem',
        'Straighten the antennas vertically',
        'If possible, move the modem closer to a window',
        'Use a mobile phone to check the signal strength in the room',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_signal_result: {
      title: 'Is the connection stable now?',
      answers: ['Yes, stable connection', 'No, still unstable'],
    },

    /* === ARBRE BADGE === */
    b_debut: {
      title: 'Is the badge reader LED on?',
      help: 'The reader is connected to the PC via USB: if its LED is off, the PC is probably off.',
      answers: ['Yes, LED on', 'No, LED off'],
      media: 'The badge reader (circled in red)',
    },
    b_pc_led: {
      title: 'Is the PC LED on?',
      answers: ['No, PC off', 'Yes, PC on'],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    b_allumer_pc: {
      title: 'Turn on the PC',
      steps: [
        'Press the Power button on the front of the PC case',
        'If nothing happens, set the ON/OFF switch at the back to ON',
        'Press the Power button again',
        'Wait 15 seconds',
      ],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    b_pc_demarre: {
      title: 'Did the PC start? (LED on)',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_multiprise: {
      title: 'Is the red LED on the internal power strip lit?',
      help: 'White power strip on the electrical panel plate, inside the machine (open the front, slide the plate forward). The PC is plugged into it: if it is off, the fault is in the power supply, not in the PC.',
      answers: ['Yes, red LED lit', 'No, power strip off'],
      media: 'Electrical panel plate: the internal power strip (white) is in the middle, below the EPI RT board',
    },
    b_led_apres_pc: {
      title: 'Is the reader LED now on?',
      answers: ['Yes', 'No'],
    },
    b_usb_rebranch: {
      title: 'Disconnect and reconnect the reader USB cable',
      steps: [
        'Unplug the USB cable from the reader on the PC side',
        'Wait 5 seconds',
        'Firmly reconnect to the same USB port',
        'Observe if the reader LED turns on',
      ],
    },
    b_led_apres_usb: {
      title: 'Is the reader LED now on?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_autre_port_usb: {
      title: 'Try another USB port',
      steps: [
        'Unplug the reader USB cable',
        'Plug it into another USB port on the PC',
        'Observe if the reader LED turns on',
      ],
    },
    b_led_autre_port: {
      title: 'Did the LED turn on on the new port?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_symptome: {
      title: 'What happens when the badge is presented?',
      help: 'The reader beeps when it reads a badge.',
      answers: [
        'Nothing: no beep, no reaction',
        'Beep, but nothing happens on the screen',
        'The screen shows "INITIALISATION BADGE" and "Tapez votre code !" (enter your code)',
        'Badge read but refused, wrong name or wrong number',
        'Random / intermittent reading',
      ],
    },
    b_autre_badge: {
      title: 'Test with another badge',
      steps: [
        "Take a badge that works (maintenance badge or a colleague's badge)",
        'Present it in front of the reader',
        'Listen for the beep and watch the screen',
      ],
    },
    b_autre_badge_result: {
      title: 'Is the other badge read?',
      answers: ['Yes, the other badge is read', 'No, no badge is read'],
    },
    b_badge_deja_ok: {
      title: 'Has the first badge ever worked on this machine?',
      answers: ['Yes, it used to work', 'No, it is a new type of badge'],
    },
    b_notepad_langue: {
      title: 'Prepare the Notepad test: switch the keyboard to English',
      help: 'The USB reader works like a keyboard: it "types" the badge number.',
      steps: [
        'Click on the language at the bottom right of the Windows taskbar',
        'Select "ENG" (English) as the input language',
        'Open Notepad: Start → Notepad',
        'Click in the Notepad text area',
      ],
      media: 'Windows taskbar: choose ENG, English (United States)',
    },
    b_notepad_test: {
      title: 'Test badge reading on Notepad',
      steps: [
        'In Notepad (English keyboard), swipe the badge in front of the reader',
        'Observe what appears in the text area',
      ],
    },
    b_notepad_result: {
      title: 'What appears in Notepad?',
      answers: ['Characters appear (e.g.: 3A8F12B4)', 'Nothing appears'],
    },
    b_admin_base: {
      title: 'Correct the number of badge digits in Admin Base',
      help: 'Admin Base (C:\\EPI\\AdminBase.exe) manages the EPIMAT database on the machine\'s PC: do not touch any other button ("Supprimer Base" (delete database), "Restaurer Base" (restore database)…).',
      steps: [
        'Count the number of digits read in Notepad',
        'Run C:\\EPI\\AdminBase.exe',
        'Click "Connecter la base" (connect the database): the indicator turns to "CONNECTE" (connected, green)',
        'In the field under "Format Badge" (e.g. F00:XXXXXXX), each X is one digit of the badge: enter as many X as digits read',
        'Click the "Format Badge" button to confirm, then restart DistEPI',
      ],
      media: [
        'C:\\EPI folder: AdminBase.exe',
        'Admin Base connected ("CONNECTE" indicator): "Format Badge" field at the bottom right, one X per digit',
      ],
    },
    b_admin_result: {
      title: 'Is the badge now recognized in DistEPI?',
      answers: ['Yes, badge OK', 'No, still ignored'],
    },
    b_reprogrammer: {
      title: 'Reprogram the reader (1/2): find the badge technology',
      help: 'Elatec TWN4 reader, programmed with AppBlaster on the machine\'s PC. First load the "Tracer" firmware, which types the badge technology.',
      steps: [
        'Open the C:\\EPI\\TWN4DevPack480 Nouveau folder and run AppBlaster.exe',
        '"Program Firmware Image" → "Select Image" → Firmware folder → TWN4_xKx480_TRC229_Multi_Tracer.bix',
        'Click "Program Image" and wait for "Done."',
        'Windows keyboard in English (ENG), open Notepad and present the badge',
        'Write down the technology displayed (e.g. ISO14443A/MIFARE Classic)',
      ],
      media: [
        'TWN4DevPack480 folder: AppBlaster.exe and its menu ("Program Firmware Image", "New Project (Configurable)")',
        'Firmware folder: choose TWN4_xKx480_TRC229_Multi_Tracer.bix',
        '"Program Image" finished: "Done."',
        'Notepad: the reader types the badge technology (here MIFARE Classic) and its UID (hidden)',
      ],
    },
    b_reprog_projet: {
      title: 'Reprogram the reader (2/2): program it for this technology',
      steps: [
        'In AppBlaster: "New Project (Configurable)" → double-click the "Multi Keyboard V4.80, App Standard V2.04" template',
        '"Transponder Types" → choose the category (e.g. MIFARE) then the type (e.g. MIFARE Classic) → double-click to add it to "Active Transponder Types"',
        'Under the added type, "Output Format": Hexadecimal or Decimal depending on the expected number',
        'Click "Create Image", then "Program Image", and wait for "Done."',
        'Test again in Notepad (keyboard in English) by presenting the badge',
      ],
      media: [
        'New Project (Configurable): "Multi Keyboard V4.80, App Standard V2.04" template',
        'Transponder Types: MIFARE → MIFARE Classic, added to "Active Transponder Types"',
        'Output Format: Hexadecimal or Decimal',
        '"Create Image" then "Program Image": "Done." at the bottom',
      ],
    },
    b_reprogrammer_result: {
      title: 'In Notepad, is the number read the badge number?',
      answers: ['Yes', 'No: different number or reversed', 'Nothing appears'],
    },
    b_reprog_iterer: {
      title: "Adjust the reader's output format",
      help: 'Some badge numbers are read backwards: it sometimes takes several attempts.',
      steps: [
        'In the AppBlaster project, change "Output Format" (Hexadecimal ↔ Decimal)',
        'Or, in "Bit Manipulation", tick "Reverse Byte Order"',
        '"Create Image", "Program Image", then test again in Notepad',
        'Repeat until you get the right number',
      ],
      media: 'Bit Manipulation: "Reverse Byte Order"',
    },
    b_reprog_iterer_result: {
      title: 'Is the number read correct now?',
      answers: ['Yes', 'No, still not'],
    },
    b_bip_redemarrer: {
      title: 'Restart the dispenser',
      steps: [
        'Start → Shut down → Restart',
        'Wait for Windows and DistEPI to fully start',
        'Present the badge again',
      ],
    },
    b_bip_result: {
      title: 'Does the badge work after the restart?',
      answers: ['Yes', 'No'],
    },
    b_init_badge: {
      title: 'Initialize the badge (first use on this machine)',
      help: 'This screen appears when the machine cannot find the badge number: a new badge, or a number mistyped in the extranet.',
      steps: [
        'The employee types their employee number, the one on their record in the extranet',
        'Some customers use the number printed on the badge as the employee number (for example as 7 digits, leading zeros: 529545 → 0529545)',
        'Check the name displayed, then confirm with OK',
      ],
      media: '"INITIALISATION BADGE" screen: the employee types their employee number',
    },
    b_init_result: {
      title: 'Is the correct name displayed?',
      answers: ['Yes', 'No, wrong or unknown name'],
    },
    b_salarie_extranet: {
      title: 'Check the employee in the EPIMAT extranet',
      steps: [
        'Log in to https://epimat.logimatiq.com/client',
        '"Salariés" (Employees) → search for the employee',
        'Check the badge number (7 digits; watch out for typos), the profile and access to this machine',
        'Correct and save',
        'On the machine, run a synchronization: keyboard plugged into the PC, Shift + L (maintenance menu), then the "Synchroniser" (Synchronize) button',
      ],
    },
    b_salarie_result: {
      title: 'Is the badge recognized now?',
      answers: ['Yes', 'No'],
    },
    b_sync: {
      title: 'Run a synchronization and check the 4G connection',
      steps: [
        "Check that the modem's Online LED is steady blue (otherwise: Internet / modem tree)",
        "Plug a keyboard into the machine's PC",
        'Shift + L to open the maintenance menu, then click the "Synchroniser" (Synchronize) button',
        'Wait for the "synchro effectué" (synchronization done) message, then present the badge again',
      ],
    },
    b_sync_result: {
      title: 'Is the badge recognized now?',
      answers: ['Yes', 'No'],
    },
    b_mauvais_notepad: {
      title: 'Check the number read by the reader',
      steps: [
        'Present the badge to the reader',
        'The number read is displayed at the top of the DistEPI screen',
        'Compare it with the number printed on the badge',
      ],
    },
    b_mauvais_result: {
      title: 'Does the number read in Notepad match the badge?',
      answers: [
        'Yes, same number: it is entered wrongly in the database',
        'No, different number: the reader must be reprogrammed',
      ],
    },
    b_corriger_bdd: {
      title: "Correct the employee's badge number",
      steps: [
        'EPIMAT extranet → "Salariés" (Employees) → employee record → "Modifier" (Edit)',
        'Correct the badge number with the exact number of the physical badge',
        'Save',
        'On the machine: Shift + L (maintenance menu), "Synchroniser" (Synchronize) button, then test the badge again',
      ],
    },
    b_bdd_result: {
      title: 'Is the badge now correctly recognized?',
      answers: ['Yes', 'No'],
    },
    b_alea_badge: {
      title: 'Test with another badge',
      steps: [
        'Take another available badge',
        'Swipe it in front of the reader',
        'Observe whether the reading is stable with this other badge',
      ],
    },
    b_alea_badge_result: {
      title: 'Does the other badge work correctly?',
      answers: ['Yes, stable reading', 'No, same problem', 'No other badge available'],
    },
    b_alea_usb: {
      title: 'Check the reader USB cable',
      steps: [
        'Unplug the reader USB cable',
        'Inspect the cable (bends, visible damage)',
        'Firmly reconnect or replace the cable if damaged',
        'Test reading with several badges',
      ],
    },
    b_alea_usb_result: {
      title: 'Is the reading stable now?',
      answers: ['Yes, stable reading', 'No, still random'],
    },

    /* === ARBRE ALIMENTATION === */
    a_debut: {
      title: "Does the room's wall outlet supplying the machine have power?",
      help: 'Test the outlet with another device.',
      answers: ['Yes', 'No'],
    },
    a_disjoncteur_local: {
      title: "Check the circuit breaker in the room's electrical panel",
      steps: [
        'Find the circuit breaker that supplies the outlet',
        'Reset it if it has tripped',
      ],
    },
    a_disjoncteur_result: {
      title: 'Is the outlet powered again?',
      answers: ['Yes', 'No'],
    },
    a_cable_machine: {
      title: "Check the machine's mains cable",
      steps: [
        'The supplied cable comes out at the bottom of the machine',
        'Check that it is fully plugged in on the machine side and on the outlet side',
      ],
    },
    a_interrupteur: {
      title: "Check the machine's main switch",
      help: 'It has no indicator light: only its position matters.',
      steps: [
        'Open the front and slide the electrical panel plate forward',
        'On the main power supply, find the red O / I switch, next to the fuse holder',
        'If it is on O, set it to I',
      ],
      media: 'The red O / I main switch (no indicator light), next to the fuse holder',
    },
    a_machine_ok: {
      title: 'Is the machine powered on now?',
      help: 'PC LED, screen, badge reader LED.',
      answers: ['Yes', 'No'],
    },
    a_coupe_circuits: {
      title: 'On the main power supply, has a circuit breaker tripped?',
      help: 'Open the front, slide the electrical panel plate forward. The main power supply (230 VAC → 24 / 5 V DC) is at the top, with 2 resettable fuses: 24 V (3 A) and 5 V (1 A).',
      answers: ['Yes, a button has popped out', 'No'],
      media: 'Main power supply, at the top of the plate: resettable fuses 24 V (3 A) and 5 V (1 A)',
    },
    a_rearmer: {
      title: 'Reset the circuit breaker',
      steps: [
        'Press the button of the tripped circuit breaker',
        'Watch whether it trips again immediately',
      ],
      media: 'Main power supply, at the top of the plate: resettable fuses 24 V (3 A) and 5 V (1 A)',
    },
    a_rearmer_result: {
      title: 'Does the circuit breaker trip again immediately?',
      answers: ['Yes, it trips again', 'No, it holds'],
    },
    a_machine_ok2: {
      title: 'Is the machine working normally?',
      answers: ['Yes', 'No'],
    },
    a_fusible: {
      title: 'Check the fuse (4 A min / 5 A max)',
      steps: [
        'Switch off the mains: unplug the machine',
        'On the main power supply, pull out the fuse holder (black cover) with a flat screwdriver',
        'Check the fuse; if it has blown, replace it with a fuse of 4 A minimum, 5 A maximum',
        'Put the fuse holder back, then plug the machine back in',
      ],
      media: [
        'Pull out the fuse holder (black cover) with a flat screwdriver',
        'The fuse in its holder',
      ],
    },
    a_fusible_result: {
      title: 'Does the machine turn on?',
      answers: ['Yes', 'No'],
    },

    /* === ARBRE TAMBOUR === */
    t_debut: {
      title: 'What is the drum problem?',
      answers: [
        'The screen shows "EN PANNE" (out of order) / the drum no longer turns',
        'The screen shows "Disjoncteur déclenché" (circuit breaker tripped)',
        'The drum stops at the wrong column',
        'The drum overshoots the column or stops off-position',
        'An item or an object is jamming the drum',
      ],
    },
    t_rotation_manuelle: {
      title: 'Does the drum turn with the "Drum rotation" button (manual rotation)?',
      help: 'Button at the top of the frame, front right. Safety: never put your hands inside the machine while the drum is turning.',
      answers: ['No, it does not turn', 'Yes, it turns'],
    },
    t_coupe_circuit_24v: {
      title: 'Reset the 24 V circuit breaker of the main power supply',
      help: 'It is the "drum circuit breaker" of the manuals.',
      steps: [
        'Slide the electrical panel plate forward',
        'If the 24 V (3 A) circuit breaker button has popped out, press it to reset it',
        'If it trips again immediately, do not insist',
      ],
      media: 'Main power supply, at the top of the plate: resettable fuses 24 V (3 A) and 5 V (1 A)',
    },
    t_coupe_result: {
      title: 'Does the drum now turn with the "Drum rotation" button?',
      help: 'Safety: never put your hands inside the machine while the drum is turning.',
      answers: ['Yes', 'No'],
    },
    t_recaler: {
      title: 'Realign the items',
      help: 'No drum recalibration is needed: when DistEPI starts, the drum initializes by itself (it goes to the nearest column to validate the CP1 sensor and find its column number). Safety: never put your hands inside the machine while the drum is turning.',
      steps: [
        'With the "Drum rotation" button, turn the drum one full revolution',
      ],
    },
    t_test_distrib: {
      title: 'Does a test dispensing work?',
      help: 'Present a badge, choose a family then an item, OK, then "Terminer" (Finish).',
      answers: ['Yes', 'No'],
    },
    t_trappes_fermees: {
      title: 'Are all hatches properly closed?',
      help: 'The drum does not turn as long as a hatch is not detected as closed.',
      answers: ['No, a hatch is open or not fully closed', 'Yes, all closed'],
    },
    t_fermer_trappe: {
      title: 'Close the hatch',
      steps: [
        'Remove the item or obstacle preventing it from closing',
        'Close the hatch again',
      ],
    },
    t_fermer_result: {
      title: 'Is the machine working again?',
      answers: ['Yes', 'No'],
    },
    t_cable_scsi: {
      title: 'Check the white SCSI cable (PC ↔ EPI 01 board)',
      help: 'It is the link between the PC and the machine. If it is not fully seated, it causes strange faults: some sensors light up and others do not, the drum does not turn although everything looks fine. It is almost the first check to do. No need to switch the machine off.',
      steps: [
        'Find the white SCSI cable between the PC (Advantech board) and the EPI 01 board of the electrical panel',
        'Check that it is fully seated at both ends',
        'If needed, unplug it completely, then plug it back in firmly',
      ],
      media: 'Electrical panel plate pulled forward: the EPI 01 board is on the right, with its ribbon cables',
    },
    t_cable_scsi_result: {
      title: 'Is the machine working again?',
      answers: ['Yes', 'No'],
    },
    t_ouvrir_debes: {
      title: 'Open DEBES',
      help: 'STATUS box: "NoDevice … - OK" = the PC communicates with the Advantech board. Otherwise, the Advantech board number is wrong in C:\\EPI\\AUTOMAT.INI: the technician corrects it.',
      steps: [
        "Plug a keyboard into the machine's PC",
        'Close DistEPI: Shift + F keys',
        'Run C:\\EPI\\DebesEPI.exe',
        'At the end of the tests: close DEBES ("Fermeture" (Close) button) and restart DistEPI',
      ],
      media: 'DEBES: drum and hatch control buttons; FCPF (hatch closed), CPT1 to CPT6 (position) and "Sécu tambour OK" (drum safety OK) indicators',
    },
    t_debes_fcpf: {
      title: 'In DEBES, are all the FCPF indicators (hatches closed) green?',
      help: 'FCPF1 to FCPF13: "hatch closed" sensor of each hatch or door.',
      answers: ['No, an FCPF indicator is off', 'Yes, all green'],
      media: 'DEBES: drum and hatch control buttons; FCPF (hatch closed), CPT1 to CPT6 (position) and "Sécu tambour OK" (drum safety OK) indicators',
    },
    t_secu_tambour: {
      title: 'In DEBES, is the "Sécu tambour OK" (drum safety OK) indicator green?',
      help: 'If it is off while all hatches are closed, a hatch board is blocking the drum safety.',
      answers: ['No, it is off', 'Yes, it is green'],
      media: 'DEBES: drum and hatch control buttons; FCPF (hatch closed), CPT1 to CPT6 (position) and "Sécu tambour OK" (drum safety OK) indicators',
    },
    t_modele_secu: {
      title: 'Does the machine have hatches (EPIMAT 13) or latch doors (EPIMAT 14)?',
      help: 'You can see it on the front: the EPIMAT 14 has manual latch doors, driven by EPI 02 boards.',
      answers: ['Hatches (EPIMAT 13)', 'Latch doors (EPIMAT 14)'],
      media: 'EPIMAT 13: front with hatches and hatch motors (2012 manual)',
    },
    t_test_epi05: {
      title: 'Find the EPI 05 board that is blocking the drum',
      help: 'Safety: never put your hands inside the machine while the drum is turning.',
      steps: [
        'Door open, remove the cover of the EPI 05 boards',
        'Disconnect all the EPI 05 boards',
        'On the board to test, set the test configuration (DIP switches)',
        'Connect this board alone',
        'In DEBES, start "Rotation TAMBOUR" (drum rotation): if the drum turns, the board is good',
        'Restore its original configuration and repeat with the next board',
      ],
      media: [
        'The EPI 05 boards, one per hatch, behind the front (EPIMAT 13)',
        'EPI 05 board: configuration DIP switches',
      ],
    },
    t_test_epi05_result: {
      title: 'Did you find the EPI 05 board that prevents rotation?',
      answers: ['Yes', 'No'],
    },
    t_position: {
      title: 'Read the drum position in DEBES',
      steps: [
        'Close DistEPI (Shift + F, keyboard plugged in) and run DEBES (C:\\EPI\\DebesEPI.exe)',
        'Look at the "Position Colonne" box ("Column Position" on older versions)',
        'It is computed from sensors CPT1 to CPT6 (LOG 03 circuit): indicator off = hole in the disc = bit set to 1',
        'Weights: CPT1 = 1, CPT2 = 2, CPT3 = 4, CPT4 = 8, CPT5 = 16, CPT6 = 32 (e.g. CPT3 and CPT6 off = 36)',
        'Compare with the column actually facing the hatch',
      ],
      media: 'DEBES: drum and hatch control buttons; FCPF (hatch closed), CPT1 to CPT6 (position) and "Sécu tambour OK" (drum safety OK) indicators',
    },
    t_position_result: {
      title: 'Does the displayed position match the actual column?',
      answers: ['Yes', 'No'],
    },
    t_pos_scsi: {
      title: 'Check the white SCSI cable (PC ↔ EPI 01 board)',
      help: 'If this cable is not fully seated, it causes strange faults: some sensors light up and others do not. No need to switch the machine off.',
      steps: [
        'Find the white SCSI cable between the PC (Advantech board) and the EPI 01 board of the electrical panel',
        'Check that it is fully seated at both ends',
        'If needed, unplug it completely, then plug it back in firmly',
      ],
      media: 'Electrical panel plate pulled forward: the EPI 01 board is on the right, with its ribbon cables',
    },
    t_pos_scsi_result: {
      title: 'Is the position displayed in DEBES correct now?',
      answers: ['Yes', 'No'],
    },
    t_arret_cp1: {
      title: 'Does the drum stop exactly in front of the column?',
      help: 'Stopping on position is triggered by the CP1 sensor (LOG 04 circuit) when the slot of the disc passes through the fork.',
      answers: ['Yes', 'No, it stops off-position'],
    },
    t_aligner_log03: {
      title: 'Clean the disc, then check the alignment of the LOG 03 and LOG 04 sensors',
      steps: [
        'Clean the drum disc with a brush to remove the dust',
        'The 2 circuits are above the drum, in the center, on a bracket fixed to the omega rail',
        'LOG 03: the 6 sensors must be aligned with the holes of the disc',
        'LOG 04: the fork must be aligned with the slot of the disc, without rubbing against the disc',
        'If needed, loosen the circuit and shift it slightly',
      ],
      media: 'The LOG 03 / LOG 04 circuits above the drum, on their bracket',
    },
    t_aligner_result: {
      title: 'Is the position correct now?',
      answers: ['Yes', 'No'],
    },
    t_vitesse: {
      title: 'Adjust the drum low speed (GR76 board)',
      help: 'The drum overshoots the column or stops off-position: adjust its low speed. Safety: never put your hands inside the machine while the drum is turning.',
      steps: [
        'On the electrical panel, find the GR76 board (black heat sink; "GR 74" on the photos of the old manuals, it is the same board)',
        'Blue single-turn potentiometer: clockwise = slower, counterclockwise = faster',
        'Turn it a quarter turn between each test',
        'Test in DEBES (DistEPI closed with Shift + F) with "Vitesse Lente TAMBOUR" (drum low speed) and "Rotation TAMBOUR" (drum rotation)',
      ],
      media: 'GR76 board: blue low-speed potentiometer',
    },
    t_vitesse_result: {
      title: 'Does the drum stop correctly at each column?',
      answers: ['Yes', 'No'],
    },
    t_vit_scsi: {
      title: 'Check the white SCSI cable (PC ↔ EPI 01 board)',
      help: 'If this cable is not fully seated, it causes strange faults: some sensors light up and others do not. No need to switch the machine off.',
      steps: [
        'Find the white SCSI cable between the PC (Advantech board) and the EPI 01 board of the electrical panel',
        'Check that it is fully seated at both ends',
        'If needed, unplug it completely, then plug it back in firmly',
      ],
      media: 'Electrical panel plate pulled forward: the EPI 01 board is on the right, with its ribbon cables',
    },
    t_vit_scsi_result: {
      title: 'Does the drum stop correctly now?',
      answers: ['Yes', 'No'],
    },
    t_bloque: {
      title: 'Free the drum',
      help: 'Safety: never put your hands inside the machine while the drum is turning.',
      steps: [
        'Remove the jammed item or object',
        'If the 24 V circuit breaker of the main power supply has tripped, reset it',
        'Turn the drum one full revolution with the "Drum rotation" button to realign the items',
      ],
    },

    /* === ARBRE TRAPPE === */
    tr_debut: {
      title: 'What is the hatch problem?',
      answers: [
        'The screen shows "Problème de distribution" (dispensing problem) after an item is confirmed',
        'The hatch LED lights up but the hatch stays locked',
        'The hatch opens but the compartment is empty',
        'A hatch does not close, or the screen shows "Fermer la trappe" (close the hatch)',
      ],
    },
    tr_debes_test: {
      title: 'Test the hatch (or the door) in DEBES',
      help: 'Same test on the EPIMAT 13 (hatches) and the EPIMAT 14 (doors).',
      steps: [
        'Note the hatch number (hatch 1 = bottom)',
        'Close DistEPI (Shift + F, keyboard plugged in) and run DEBES (C:\\EPI\\DebesEPI.exe)',
        'Click "Trappe N Ouvrir" (open hatch N) then "N Fermer" (close N)',
        'Watch the FCPF N (hatch closed) and FCPO (hatch open) indicators',
        'At the end: close DEBES ("Fermeture" (Close)) and restart DistEPI',
      ],
      media: 'DEBES: drum and hatch control buttons; FCPF (hatch closed), CPT1 to CPT6 (position) and "Sécu tambour OK" (drum safety OK) indicators',
    },
    tr_debes_result: {
      title: 'Does the hatch open and close with DEBES?',
      answers: ['Yes', 'No'],
    },
    tr_scsi: {
      title: 'Check the white SCSI cable (PC ↔ EPI 01 board)',
      help: 'If this cable is not fully seated, it causes strange faults: some sensors light up and others do not. No need to switch the machine off.',
      steps: [
        'Find the white SCSI cable between the PC (Advantech board) and the EPI 01 board of the electrical panel',
        'Check that it is fully seated at both ends',
        'If needed, unplug it completely, then plug it back in firmly',
      ],
      media: 'Electrical panel plate pulled forward: the EPI 01 board is on the right, with its ribbon cables',
    },
    tr_scsi_result: {
      title: 'Does the hatch now open and close with DEBES?',
      answers: ['Yes', 'No'],
    },
    tr_modele: {
      title: 'Does the machine have hatches (EPIMAT 13) or latch doors (EPIMAT 14)?',
      help: 'You can see it on the front: the EPIMAT 14 has manual latch doors, driven by EPI 02 boards.',
      answers: ['Hatches (EPIMAT 13)', 'Latch doors (EPIMAT 14)'],
      media: 'EPIMAT 13: front with hatches and hatch motors (2012 manual)',
    },
    tr_obstacle: {
      title: 'Check the hatch, then try a dispensing again',
      steps: [
        'Check that no item is preventing it from opening or closing',
        'Run a test dispensing again',
      ],
    },
    tr_obstacle_result: {
      title: 'Does the dispensing work?',
      answers: ['Yes', 'No'],
    },
    tr_motorisee: {
      title: 'Does the hatch open by itself (motorized hatch)?',
      help: 'On the EPIMAT 13, hatches are motorized or manual depending on the machine (MANUEL parameter of DistEPI).',
      answers: ['Yes, motorized', 'No, the user opens it after it is unlocked'],
    },
    tr_verif_moteur: {
      title: 'Check the hatch motor',
      steps: [
        'Remove the protective cover (3 M4 screws, 7 mm wrench)',
        "Check the MOTOR connector on the hatch's EPI 05 board",
        "Check that there is no play between the motor pinion and the hatch's white rack",
        'Test again in DEBES',
      ],
      media: 'Hatch motor and its EPI 05 board (EPIMAT 13)',
    },
    tr_moteur_result: {
      title: 'Does the hatch work?',
      answers: ['Yes', 'No'],
    },
    tr_verif_verrou: {
      title: 'Check the electric lock of the hatch',
      steps: [
        'Remove the protective cover (3 M4 screws, 7 mm wrench)',
        "Check the LOCK connector (electromagnet) on the hatch's EPI 05 board",
        'Test the opening again in DEBES',
      ],
      media: 'EPI 05 board: MOTOR and LOCK connectors at the bottom',
    },
    tr_verrou_result: {
      title: 'Does the hatch work?',
      answers: ['Yes', 'No'],
    },
    tr_casier_vide: {
      title: 'Check the stock of this location',
      steps: [
        'Note the column and level concerned',
        'Correct the stock from the refill menu (maintenance badge → "Vider / Remplir" (Empty / Fill))',
        'Check the content of the location in the extranet ("Machines")',
      ],
    },
    tr_casier_result: {
      title: 'Does the problem happen again at this location?',
      answers: ['No', 'Yes'],
    },
    tr_capteur: {
      title: 'In DEBES, does the FCPF indicator of this hatch light up when you close it by hand?',
      help: 'FCPF = "hatch closed" sensor. If DEBES is not open: close DistEPI (Shift + F), then run C:\\EPI\\DebesEPI.exe.',
      answers: ['No, it stays off', 'Yes'],
      media: 'DEBES: drum and hatch control buttons; FCPF (hatch closed), CPT1 to CPT6 (position) and "Sécu tambour OK" (drum safety OK) indicators',
    },
    tr_capteur_scsi: {
      title: 'Check the white SCSI cable (PC ↔ EPI 01 board)',
      help: 'If this cable is not fully seated, it causes strange faults: some sensors light up and others do not. No need to switch the machine off.',
      steps: [
        'Find the white SCSI cable between the PC (Advantech board) and the EPI 01 board of the electrical panel',
        'Check that it is fully seated at both ends',
        'If needed, unplug it completely, then plug it back in firmly',
      ],
      media: 'Electrical panel plate pulled forward: the EPI 01 board is on the right, with its ribbon cables',
    },
    tr_capteur_scsi_result: {
      title: 'Does the FCPF indicator now light up when the hatch is closed?',
      answers: ['Yes', 'No, it stays off'],
    },
    tr_modele_capteur: {
      title: 'Does the machine have hatches (EPIMAT 13) or latch doors (EPIMAT 14)?',
      help: 'You can see it on the front: the EPIMAT 14 has manual latch doors, driven by EPI 02 boards.',
      answers: ['Hatches (EPIMAT 13)', 'Latch doors (EPIMAT 14)'],
      media: 'EPIMAT 13: front with hatches and hatch motors (2012 manual)',
    },

    /* === ARBRE LOGICIEL DÉMARRAGE === */
    ld_debut: {
      title: 'What is happening?',
      answers: [
        'DistEPI does not start (Windows desktop visible)',
        'DistEPI closes by itself or freezes',
        'The screen shows "EN PANNE" (out of order)',
        'Windows or BIOS error message',
      ],
    },
    ld_redemarrer_distepi: {
      title: 'Restart DistEPI',
      steps: [
        'Close DistEPI (Shift + F, keyboard plugged in)',
        'Start it again (desktop icon or C:\\EPI\\DistEPI.exe)',
      ],
    },
    ld_redemarrer_result: {
      title: 'Is DistEPI working normally?',
      answers: ['Yes', 'No'],
    },

    /* === ARBRE LOGICIEL SYNCHRO === */
    ls_debut: {
      title: 'What is the symptom?',
      answers: [
        'An employee, an item or a profile created in the extranet does not reach the machine',
        'The items do not appear in the selection',
        'The dispensings do not reach the extranet',
        'Synchronization error message',
      ],
    },
    ls_intervalle: {
      title: 'Run a synchronization',
      steps: [
        'The machine fetches the extranet updates at regular intervals (IntervalGSMServer parameter)',
        'To avoid waiting: keyboard plugged into the PC, Shift + L (maintenance menu), then the "Synchroniser" (Synchronize) button',
        'Wait for the "synchro effectué" (synchronization done) message',
      ],
    },
    ls_intervalle_result: {
      title: 'Has the update reached the machine?',
      answers: ['Yes', 'No'],
    },
    ls_casiers: {
      title: 'Check the compartment configuration in the extranet',
      steps: [
        'Extranet → "Machines" → click on the machine',
        'Check that the item is assigned to a compartment, a column or a level',
        'Check the filling of the location',
      ],
    },
    ls_casiers_result: {
      title: 'Do the items appear now?',
      answers: ['Yes', 'No'],
    },
    ls_online: {
      title: 'Is the modem\'s "Online" LED steady blue?',
      answers: ['No', 'Yes'],
    },

    /* === ARBRE LOGICIEL CONFIGURATION === */
    lc_debut: {
      title: 'What should be checked in the DistEPI settings?',
      help: 'To open the settings, with a keyboard plugged into the PC: Shift + L opens the maintenance menu, then click in the top right corner of the screen, in the empty white area, to show the hidden menu.',
      answers: [
        'The touchscreen does not react in DistEPI',
        'The badge reader is not taken into account',
        'The machine does not synchronize with the cloud',
        'The number of compartments does not match the machine',
      ],
    },
    lc_tactile: {
      title: 'Check the "EcranTactile" (touchscreen) setting',
      steps: [
        'DistEPI settings → Machine tab',
        '"EcranTactile" must be enabled',
        'Save and restart DistEPI',
      ],
    },
    lc_badge: {
      title: 'Check the badge reader type',
      steps: [
        'DistEPI settings → Badge tab → "TypeLecteurBadge" must be 10 (USB reader in keyboard emulation)',
        'Save and restart DistEPI',
      ],
    },
    lc_cloud: {
      title: 'Check the cloud settings',
      steps: [
        '"MachineServeur": always ticked for cloud machines',
        '"VersionGSM": enabled for the cloud',
        '"VersionHTML5": required for the cloud',
        'Save and restart DistEPI',
      ],
    },
    lc_type: {
      title: 'Check the machine type',
      steps: [
        'DistEPI settings → Type tab → "Machine1"',
        'TYPE 1 = 32 compartments, 2 = 90, 3 = 180, 4 = 126, 5 = 252, 6 = Mix or 468, 8 = 432, 10 = 806 or Mix 806, 12 = Slim/Baby',
        'Save and restart DistEPI',
      ],
    },
    lc_result: {
      title: 'Is the problem solved?',
      answers: ['Yes', 'No'],
    },

    /* === SOLUTIONS === */
    sol_resolved: {
      title: 'Problem resolved',
      message: 'The machine is working correctly again. Remember to close the support ticket if applicable.',
    },
    sol_sav: {
      title: 'Contact Support',
      message: 'The problem persists after the checks. Contact Logimatiq Support and send them the diagnostic report.',
    },
    sol_disjoncteur: {
      title: 'Power / circuit breaker issue',
      message: "The room's wall outlet is not powered. Check the connections and the circuit breaker in the electrical panel of the room. If the breaker is OK, contact Support.",
    },
    sol_changer_pc: {
      title: 'Replace the integrated PC',
      message: 'The PC no longer starts despite the checks. Replace the PC, check that everything works with DEBES, and contact Support.',
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    sol_changer_ecran: {
      title: 'Replace the screen',
      message: 'The screen remains faulty after the checks. Replace it (remove the protective plate, disconnect, unscrew) and contact Support.',
    },
    sol_changer_alim: {
      title: "Replace the screen's power supply unit",
      message: 'The screen turns back on with a new power supply: the old unit was faulty. Report the replaced part to Support.',
    },
    sol_changer_alim_generale: {
      title: 'Replace the main power supply',
      message: 'The main power supply (230 VAC → 24 / 5 V DC, at the top of the electrical panel plate) no longer delivers voltage. Replace it and contact Support.',
      media: 'Electrical panel plate: the main power supply is at the top',
    },
    sol_court_circuit: {
      title: 'Short circuit or jam: do not insist',
      message: 'The circuit breaker trips again immediately: probable short circuit or jam. Do not reset it again. Contact Support.',
    },
    sol_changer_modem: {
      title: 'Replace the GSM modem',
      message: 'The modem no longer connects despite the checks. Before unplugging it, note its APN (PC browser → 192.168.1.1 → Setup): the new modem must have the same APN if the same SIM card is kept. Replace it (keep the SIM, disconnect the power supply and the antennas) and contact Support.',
    },
    sol_antenne_ext: {
      title: 'Install an external antenna',
      message: 'The GSM signal is insufficient in this location. An external remote antenna is needed. Contact Support for installation.',
    },
    sol_sav_serveur: {
      title: 'Logimatiq server issue',
      message: 'The ClientSynch DB EPI test fails: the issue is with the Logimatiq server or the SQL database. Contact Logimatiq Support.',
    },
    sol_changer_lecteur: {
      title: 'Replace the badge reader',
      message: 'The badge reader is faulty. Replace it (move the connector over to the new reader), check that it beeps when a badge is presented, and contact Support.',
      media: 'The badge reader seen from inside the door (circled in orange)',
    },
    sol_badge_defaillant: {
      title: 'Faulty badge to replace',
      message: 'This specific badge is defective (other badges work). Replace the badge through Support.',
    },
    sol_sav_tambour: {
      title: 'Drum: Support intervention',
      message: 'To be checked by Support: 24 V circuit breaker (drum circuit breaker), M1 motor, drum rotation board (EPI RT), low-speed board (GR76).',
    },
    sol_changer_epi05: {
      title: 'Replace the EPI 05 hatch board',
      message: 'Faulty EPI 05 board. Replace it (repair kit) by copying exactly the jumpers and switches of the old board ("do not forget to change the jumpers"). Contact Support.',
      media: 'EPI 05 board: MOTOR and LOCK connectors at the bottom',
    },
    sol_changer_log03: {
      title: 'Replace the drum disc sensor (LOG 03 / LOG 04)',
      message: 'Replace the faulty circuit (LOG 03: sensors CPT1-CPT6; LOG 04: CP1, 14-wire ribbon cable to the main board). Contact Support.',
    },
    sol_sav_epi02: {
      title: 'EPIMAT 14: to be checked by Support',
      message: 'On the EPIMAT 14 (latch doors, EPI 02 boards), the rest of the diagnostic is not yet described in the app. Contact Support and send them the diagnostic report.',
    },
    sol_condamner_trappe: {
      title: 'Faulty hatch: disable it, then Support',
      message: 'Disable this hatch in DistEPI to keep using the machine, then contact Support for the repair.',
    },
    tbd: {
      title: 'Tree to complete',
      message: 'This machine does not yet have a diagnostic tree. Contact Support directly.',
    },
  },
};
