/* ============================================================================
   ENGLISH TRANSLATIONS
   ui   → chaînes d'interface (clé = texte français)
   nodes → contenu des nœuds de l'arbre de diagnostic
   ========================================================================== */
export const EN = {

  /* ---- Chaînes d'interface ---- */
  ui: {
    // Splash
    'Démarrer un diagnostic': 'Start a diagnostic',
    'Diagnostic pas à pas': 'Step-by-step diagnostic',
    'Guide de diagnostic pas à pas pour techniciens et clients':
      'Step-by-step diagnostic guide for technicians and customers',
    'v0.2 · usage interne Logimatiq': 'v0.2 · Logimatiq internal use',

    // Login
    'Connexion': 'Login',
    'Identifiants fournis par Logimatiq': 'Credentials provided by Logimatiq',
    'Identifiant': 'Username',
    'Votre login': 'Your username',
    'Mot de passe': 'Password',
    'Votre mot de passe': 'Your password',
    '⚠ Identifiant ou mot de passe incorrect.': '⚠ Incorrect username or password.',
    'Se connecter →': 'Sign in →',
    'Contactez Logimatiq pour obtenir vos identifiants':
      'Contact Logimatiq to get your credentials',

    // Home
    'Connectez-vous': 'Sign in',
    'Chercher un symptôme, une fiche…': 'Search for a symptom, a guide…',
    'Démarrer un diagnostic': 'Start a diagnostic',
    'Bientôt disponible': 'Coming soon',
    'Guide de mise en service': 'Installation guide',
    'Checklist installation EPIMAT': 'EPIMAT installation checklist',
    'Récents': 'Recent',
    'Aucun diagnostic récent': 'No recent diagnostics',
    'Les diagnostics terminés apparaîtront ici':
      'Completed diagnostics will appear here',

    // Bottom nav
    'Accueil': 'Home',
    'Fiches': 'Guides',
    'Historique': 'History',

    // Symptoms
    'Quel est le problème ?': 'What is the problem?',
    'Affichage': 'Display',
    'Réseau': 'Network',
    'Badge': 'Badge',
    'Logiciel': 'Software',
    'Config': 'Config',

    // Machine select
    'Quelle machine ?': 'Which machine?',
    'Machines enregistrées': 'Registered machines',
    'Nouvelle machine': 'New machine',
    '← Retour à la liste': '← Back to list',
    'Numéro de série *': 'Serial number *',
    'Ex : EPM-2024-0042': 'E.g.: EPM-2024-0042',
    'Site / Emplacement': 'Site / Location',
    'Ex : Entrepôt Paris, Rayon 3…': 'E.g.: Paris Warehouse, Row 3…',
    'Client / Société': 'Customer / Company',
    'Nom du client final': 'End customer name',
    '⚠ Le numéro de série est obligatoire.': '⚠ Serial number is required.',
    'Enregistrer et continuer →': 'Save and continue →',

    // Diag UI
    'Étape': 'Step',
    'étapes': 'steps',
    'Procédure faite': 'Done',
    'Question': 'Question',
    'Procédure': 'Procedure',
    '← Retour': '← Back',
    "C'est fait ✓": 'Done ✓',
    'Quitter': 'Quit',
    'Quitter ce diagnostic ?': 'Quit this diagnostic?',
    'Se déconnecter ?': 'Sign out?',
    'Cheminement du diagnostic': 'Diagnostic path',
    'Copier le rapport': 'Copy report',
    '✓ Copié !': '✓ Copied!',
    'Contacter le SAV Logimatiq': 'Contact Logimatiq Support',
    'Refaire ce diagnostic': 'Redo this diagnostic',
    'Terminer': 'Done',
    'Nœud introuvable.': 'Node not found.',
    'SAV': 'Support',

    // Rapport
    '🔧 RAPPORT DIAGNOSTIC LOGIMATIQ': '🔧 LOGIMATIQ DIAGNOSTIC REPORT',
    'Machine  :': 'Machine  :',
    'Problème :': 'Problem  :',
    'Date     :': 'Date     :',
    'Généré par Logimatiq SAV App': 'Generated by Logimatiq Support App',
    'Rapport diagnostic Logimatiq': 'Logimatiq Diagnostic Report',

    // Outcome pills
    'Résolu': 'Resolved',
    'Pièce': 'Part',

    // History
    'Aucun diagnostic terminé': 'No completed diagnostics',
    'Les diagnostics complétés apparaîtront ici':
      'Completed diagnostics will appear here',
    'Total': 'Total',
    'Résolus': 'Resolved',
    'Taux': 'Rate',

    // Stats
    'Aucune donnée disponible': 'No data available',
    'Effectuez des diagnostics pour voir les statistiques':
      'Run diagnostics to see statistics',
    'Diagnostics': 'Diagnostics',
    'Machines': 'Machines',
    'Répartition des résultats': 'Result breakdown',
    'SAV requis': 'Support needed',
    'Pièce à changer': 'Part to replace',
    'Machines les plus actives': 'Most active machines',
    'Sociétés les plus actives': 'Most active companies',
    'Pannes les plus fréquentes': 'Most common faults',

    // Setup
    'Mise en service': 'Installation',
    'Base de connaissances': 'Knowledge base',
    'Progression': 'Progress',
    '✓ Complété': '✓ Completed',
    '✓ Installation complète !': '✓ Installation complete!',
    'La machine est prête à l\'utilisation.': 'The machine is ready to use.',
    'Réinitialiser la checklist': 'Reset checklist',
    'Réinitialiser toute la checklist d\'installation ?': 'Reset the entire installation checklist?',

    // Faults
    'Pannes': 'Faults',
    'Pannes récurrentes': 'Recurring faults',
    'Rechercher une panne…': 'Search for a fault…',
    'Tout': 'All',
    'Symptômes': 'Symptoms',
    'Étapes de résolution': 'Resolution steps',
    'Photo à venir': 'Photo coming soon',
    'Appeler le SAV Logimatiq': 'Call Logimatiq Support',
    'Aucune panne trouvée': 'No fault found',
    'Essayez un autre mot-clé': 'Try another keyword',
    'Critique': 'Critical',
    'Urgent': 'Urgent',
    'Courant': 'Common',

    // KB
    'Fiches PDF': 'PDF Guides',
    'Codes erreur': 'Error codes',
    'écran noir, modem, badge…': 'black screen, modem, badge…',
    'ERR_SYNC, badge, réseau…': 'ERR_SYNC, badge, network…',
    'Aucun résultat pour': 'No results for',

    // User roles
    'Client': 'Customer',
    'Technicien revendeur': 'Reseller technician',
    'Technicien Logimatiq': 'Logimatiq technician',

    // Toolbar / headers statiques HTML
    'Statistiques': 'Statistics',
    'Se déconnecter': 'Sign out',
    'Logimatiq SAV': 'Logimatiq Support',
    'Tableau de bord': 'Dashboard',
    'EPIMAT': 'EPIMAT',
  },

  /* ---- Titres des symptômes (tree.js symptoms[]) ---- */
  symptoms: {
    't.epimat.screen':   'Black screen / no image / sync issue',
    't.epimat.internet': 'No internet connection / modem offline',
    't.epimat.badge':    'Badge not read / wrong number / erratic reading',
    't.log.demarrage':   "Software won't start / crashes",
    't.log.synchro':     'Software synchronization error',
    't.log.impression':  'Printing problem',
    't.log.config':      'Configuration / initial setup',
    't.vet.ph':          'To complete',
  },

  /* ---- Nœuds de l'arbre de diagnostic ---- */
  nodes: {

    /* === ARBRE ÉCRAN === */
    s_debut: {
      title: 'Is the machine plugged into the power outlet?',
      help: 'Check that the main power cable is properly connected to the power strip.',
      answers: ['Yes, plugged in', 'No, unplugged'],
    },
    s_brancher: {
      title: 'Connect the machine to the power outlet',
      steps: [
        'Check that the power strip is on (red indicator lit)',
        'Firmly connect the power cable on the machine side',
        'Connect the other end to the power strip',
        'Wait 10 seconds',
      ],
    },
    s_led_ecran: {
      title: 'What is the color of the screen LED indicator?',
      help: 'Small indicator on the front of the monitor, at the bottom or side.',
      answers: ['Red', 'Off (no LED)', 'Green (image visible, other problem)'],
    },
    s_rouge_pc_led: {
      title: 'Is the PC LED on?',
      help: 'Light indicator on the front of the PC case built into the machine.',
      answers: ['Yes, PC LED on', 'No, PC off'],
    },
    s_rouge_pc_ventilo: {
      title: 'Check the PC power supply',
      steps: [
        'Listen or look if the PC fan is running (ventilation grills)',
        'Go to the back of the PC case',
        'Locate the small ON/OFF switch near the PC power socket',
        'Switch to OFF, wait 5 seconds, then switch back to ON',
        'Return to the front and press the PC Power button',
        'Wait 15 seconds',
      ],
    },
    s_rouge_pc_demarre: {
      title: 'Did the PC start? (LED on)',
      answers: ['Yes, LED on', 'No, still off'],
    },
    s_rouge_rebrancher_vga: {
      title: 'Disconnect and reconnect the VGA cable',
      steps: [
        'Locate the VGA cable (blue screw connector) between screen and PC',
        'Unplug the cable on the screen side, then on the PC side',
        'Firmly reconnect on both sides and tighten the thumbscrews',
        'Wait 10 seconds',
      ],
    },
    s_rouge_vga_result: {
      title: 'Has the image returned on the screen?',
      answers: ['Yes, image OK', 'No, still red'],
    },
    s_rouge_changer_vga: {
      title: 'Replace the VGA cable',
      steps: [
        'Unplug the old VGA cable from both sides',
        'Connect a new VGA cable on the PC side, then on the screen side',
        'Tighten the thumbscrews',
        'Wait for the image to return (10 seconds)',
      ],
    },
    s_rouge_apres_changer_vga: {
      title: 'Is the image now visible?',
      answers: ['Yes, image OK', 'No, screen red'],
    },
    s_eteint_cable: {
      title: 'Is the screen power cable properly connected?',
      help: 'Check the cable connecting the screen to the power strip or power supply.',
      answers: ['Yes, connected', 'No, disconnected'],
    },
    s_eteint_brancher_cable: {
      title: 'Connect the screen power cable',
      steps: [
        'Locate the screen power cable',
        'Firmly connect the end on the screen side',
        'Connect the other end to the power strip',
      ],
    },
    s_eteint_multiprise: {
      title: 'Is the red LED on the power strip lit?',
      help: 'The power strip must show a red indicator to confirm it is powered.',
      answers: ['Yes, red LED lit', 'No, power strip off'],
    },
    s_eteint_changer_alim: {
      title: 'Replace the screen power supply',
      steps: [
        'Locate the screen power supply (black box on the cable)',
        'Unplug the faulty power supply',
        'Connect a new power supply of the same reference',
        'Turn the screen back on',
      ],
    },
    s_eteint_alim_result: {
      title: 'Did the screen turn on?',
      answers: ['Yes, screen on', 'No, still off'],
    },
    s_vert_symptome: {
      title: 'What is the exact problem?',
      answers: [
        'Flickering or color problem',
        'Touchscreen not responding',
        'DistEPI is not launched (desktop visible)',
        'Wrong display resolution',
        'Screen frozen / stuck',
      ],
    },
    s_vert_vga: {
      title: 'Check the VGA cable',
      steps: [
        'Locate the VGA cable (blue connector) between screen and PC',
        'Unplug and firmly reconnect on both sides',
        'Tighten the thumbscrews',
      ],
    },
    s_vert_vga_result: {
      title: 'Has the image problem disappeared?',
      answers: ['Yes, stable image', 'No, problem persists'],
    },
    s_vert_usb: {
      title: 'Check the USB cable between screen and PC',
      steps: [
        'Locate the USB cable connecting the screen to the PC (needed for touch)',
        'Unplug and firmly reconnect on both sides',
        'If possible, try another USB port on the PC',
      ],
    },
    s_vert_usb_result: {
      title: 'Is the touchscreen responding now?',
      answers: ['Yes, touch OK', 'No, still inactive'],
    },
    s_vert_distepi: {
      title: 'Launch the DistEPI software',
      steps: [
        'On the Windows desktop, find the DistEPI icon',
        'Double-click to launch the application',
        'Wait for full loading (about 30 seconds)',
      ],
    },
    s_vert_distepi_result: {
      title: 'Did DistEPI launch correctly?',
      answers: ['Yes, DistEPI launched', "No, won't open"],
    },
    s_vert_resolution: {
      title: 'Fix the resolution (1280 × 720)',
      steps: [
        'Right-click on the Windows desktop',
        'Click "Display settings"',
        'Under Resolution, select 1280 × 720',
        'Click "Keep changes"',
      ],
    },
    s_vert_resolution_result: {
      title: 'Is the resolution correct now?',
      answers: ['Yes, display correct', 'No, still incorrect'],
    },
    s_vert_redemarrer: {
      title: 'Restart the machine',
      steps: [
        'Click Start → Shut down → Restart',
        'If screen is frozen: hold the Power button for 5 seconds to force shutdown',
        'Turn back on with the Power button',
        'Wait for Windows to fully restart',
        'Check that DistEPI restarts automatically',
      ],
    },
    s_vert_redemarrer_result: {
      title: 'Is the machine working correctly after restart?',
      answers: ['Yes, everything OK', 'No, problem persists'],
    },

    /* === ARBRE INTERNET === */
    i_debut: {
      title: 'What is the problem?',
      help: 'Check the blue "online" LED on the Four-Faith F3827 modem.',
      answers: [
        'Modem "online" LED is off',
        '"Online" LED on but DistEPI sync error',
        'Frequent disconnections / unstable signal',
      ],
    },
    i_reboot_modem: {
      title: 'Restart the modem',
      steps: [
        'Locate the ON/OFF switch on the modem power supply',
        'Switch to OFF (or unplug the power socket)',
        'Wait 30 seconds',
        'Turn back on (switch to ON or reconnect)',
        'Wait 2 to 3 minutes for the modem to reconnect to the GSM network',
      ],
    },
    i_reboot_result: {
      title: 'Is the "online" LED now on?',
      answers: ['Yes, blue LED on', 'No, still off'],
    },
    i_antennes_check: {
      title: 'Check the 2 modem antennas',
      steps: [
        'Check that both GSM antennas are properly screwed onto the modem',
        'If an antenna is loose, screw it back firmly',
        'Wait 1 minute and observe the online LED',
      ],
    },
    i_antennes_result: {
      title: 'Did the "online" LED turn on?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    i_sim_led: {
      title: 'Is the modem SIM LED on?',
      help: '"SIM" indicator on the front of the modem (see photo).',
      answers: ['Yes, SIM LED on', 'No, SIM LED off'],
    },
    i_reinsertion_sim: {
      title: 'Re-insert the SIM card',
      steps: [
        'Turn off the modem',
        'Locate the small SIM ejection hole on the modem',
        'Insert a pin, rivet or pen tip into the hole to eject the SIM',
        'Remove the SIM and clean the gold contacts with a dry cloth',
        'Re-insert the SIM and turn the modem back on',
        'Wait 2 to 3 minutes',
      ],
    },
    i_sim_result: {
      title: 'Is the SIM LED now on?',
      answers: ['Yes, SIM LED on', 'No, still off'],
    },
    i_setup_grizzly: {
      title: 'Launch the Grizzly setup (setup17)',
      steps: [
        'On the Windows desktop, open the Grizzly Setup17 program',
        'Follow the reconfiguration procedure — the program automatically resets the APN (wbdata / matooma / orange)',
        'Wait for the setup to complete and the modem to restart automatically if prompted',
        'Wait 2 to 3 minutes then observe the online LED',
      ],
    },
    i_setup_result: {
      title: 'Is the "online" LED now on?',
      answers: ['Yes, blue LED on', 'No, still off'],
    },
    i_connexion_distante: {
      title: "Can we connect remotely to the machine's PC?",
      help: 'If remote connection works, the RJ45 cable is not the cause.',
      answers: ['Yes, remote connection OK', 'No, no remote connection'],
    },
    i_rj45_check: {
      title: 'Check the RJ45 cable (PC ↔ Modem)',
      steps: [
        'Locate the RJ45 cable connecting the PC to the modem',
        'Unplug and reconnect firmly on both ends until it clicks',
        'Check that the Windows PC shows an internet connection',
      ],
    },
    i_rj45_result: {
      title: 'Does the Windows PC now have internet access?',
      answers: ['Yes, internet OK', 'No, still no network'],
    },
    i_clientsynch: {
      title: 'Test with ClientSynch DB EPI (Grizzly)',
      steps: [
        'On the Windows desktop, open the ClientSynch DB EPI software',
        'Run the data receive and send test',
        'Observe whether the test passes or fails',
      ],
    },
    i_clientsynch_result: {
      title: 'Did the ClientSynch test succeed?',
      answers: ['Yes, test OK', 'No, test fails'],
    },
    i_reboot_pc_distepi: {
      title: 'Restart the PC',
      steps: [
        'Click Start → Shut down → Restart',
        'Wait for Windows to fully restart',
        'Check that DistEPI restarts and sync works',
      ],
    },
    i_reboot_distepi_result: {
      title: 'Is DistEPI working correctly after restart?',
      answers: ['Yes, sync OK', 'No, error persists'],
    },
    i_signal_faible: {
      title: 'Check antennas and reposition the modem',
      steps: [
        'Check that both GSM antennas are properly screwed onto the modem',
        'Straighten the antennas vertically',
        'If possible, move the modem closer to a window to improve the GSM signal',
        'Test with a mobile phone to assess signal strength in the room',
      ],
    },
    i_signal_result: {
      title: 'Is the connection stable now?',
      answers: ['Yes, stable connection', 'No, still unstable'],
    },

    /* === ARBRE BADGE === */
    b_debut: {
      title: 'Is the badge reader LED on?',
      help: 'The reader is connected via USB to the PC — if LED is off, the PC is probably off.',
      answers: ['Yes, LED on', 'No, LED off'],
    },
    b_pc_led: {
      title: 'Is the PC LED on?',
      help: 'Light indicator on the front of the integrated PC case.',
      answers: ['No, PC off', 'Yes, PC on'],
    },
    b_allumer_pc: {
      title: 'Turn on the PC',
      steps: [
        'Press the Power button on the front of the PC case',
        'If nothing happens, go to the back of the PC',
        'Check the ON/OFF switch and set it to ON',
        'Return to the front and press the Power button again',
        'Wait 15 seconds',
      ],
    },
    b_usb_rebranch: {
      title: 'Disconnect and reconnect the reader USB cable',
      steps: [
        'Unplug the USB cable from the reader on the PC side',
        'Wait 5 seconds',
        'Firmly reconnect to the same USB port',
        'Observe if the reader LED turns on',
      ],
    },
    b_led_apres_usb: {
      title: 'Is the reader LED now on?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_autre_port_usb: {
      title: 'Try another USB port',
      steps: [
        'Unplug the reader USB cable',
        'Plug it into another USB port on the PC',
        'Observe if the reader LED turns on',
      ],
    },
    b_led_autre_port: {
      title: 'Did the LED turn on on the new port?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_symptome: {
      title: 'What is the problem with the badge?',
      answers: [
        'Badge not read — no reaction',
        'Badge read but wrong number displayed',
        'Random / intermittent reading',
      ],
    },
    b_port_com: {
      title: 'Check the COM port (Device Manager)',
      steps: [
        'Right-click "This PC" → Manage → Device Manager',
        'Open "Ports (COM & LPT)" → note the reader COM number (e.g.: COM1)',
        'Open the AUTOMAT INI file on the desktop',
        'In the [port com] section, verify "port lecteur badge" = same number',
        'If different, correct the number and save AUTOMAT INI',
      ],
    },
    b_port_com_result: {
      title: 'Is the reader now recognized (reaction when swiping badge)?',
      answers: ['Yes', 'No'],
    },
    b_notepad_langue: {
      title: 'Prepare Notepad test — switch keyboard to English',
      steps: [
        'Click on the language in the bottom right of the Windows taskbar',
        'Select "ENG" (English) as input language',
        'Open Notepad: Start → Notepad',
        'Click in the Notepad text area',
      ],
    },
    b_notepad_test: {
      title: 'Test badge reading on Notepad',
      steps: [
        'In Notepad (English keyboard), swipe the badge in front of the reader',
        'Observe what appears in the text area',
      ],
    },
    b_notepad_result: {
      title: 'What appears in Notepad?',
      answers: [
        'Hex characters appear (e.g.: 3A8F12B4)',
        'Nothing appears',
      ],
    },
    b_admin_base: {
      title: 'Fix the character count in Admin Base',
      steps: [
        'In DistEPI, go to "Admin Base"',
        'Find the badge character count parameter',
        'Count the number of characters read in Notepad',
        'Correct the parameter to match (e.g.: set 8 if Notepad reads 8 characters)',
        'Save and restart DistEPI',
      ],
    },
    b_admin_result: {
      title: 'Is the badge now recognized in DistEPI?',
      answers: ['Yes, badge OK', 'No, still ignored'],
    },
    b_reprogrammer: {
      title: 'Reprogram the badge reader',
      steps: [
        'Open the reader programming software',
        'Follow the reprogramming procedure',
        'Re-test with Notepad after reprogramming',
      ],
    },
    b_reprogrammer_result: {
      title: 'Does the reader read correctly in Notepad?',
      answers: ['Yes, characters visible', 'No, still nothing'],
    },
    b_mauvais_notepad: {
      title: 'Check the read number — Notepad test (English keyboard)',
      steps: [
        'Switch Windows keyboard to English (taskbar → ENG)',
        'Open Notepad and swipe the badge in front of the reader',
        'Compare the number displayed with the one printed on the badge',
      ],
    },
    b_mauvais_result: {
      title: 'Does the number read in Notepad match the badge?',
      answers: [
        'Yes, same number — incorrectly entered in database',
        'No, different number — reader to reprogram',
      ],
    },
    b_corriger_bdd: {
      title: 'Correct the number in the database',
      steps: [
        'In DistEPI, go to "Admin Base"',
        'Find the employee concerned',
        'Correct the registered badge number with the exact number on the physical badge',
        'Save and retest',
      ],
    },
    b_bdd_result: {
      title: 'Is the badge now correctly recognized?',
      answers: ['Yes', 'No'],
    },
    b_alea_badge: {
      title: 'Test with another badge',
      steps: [
        'Get another available Kalistrut badge',
        'Swipe it in front of the reader',
        'Observe if the reading is stable with this other badge',
      ],
    },
    b_alea_badge_result: {
      title: 'Does the other badge work correctly?',
      answers: [
        'Yes, stable reading',
        'No, same problem',
        'No other badge available',
      ],
    },
    b_alea_usb: {
      title: 'Check the reader USB cable',
      steps: [
        'Unplug the reader USB cable',
        'Inspect the cable (bends, visible damage)',
        'Firmly reconnect or replace the cable if damaged',
        'Test reading with several badges',
      ],
    },
    b_alea_usb_result: {
      title: 'Is the reading stable now?',
      answers: ['Yes, stable reading', 'No, still random'],
    },

    /* === SOLUTIONS === */
    sol_resolved: {
      title: 'Problem resolved',
      message: 'The machine is working correctly again. Remember to close the support ticket if applicable.',
    },
    sol_disjoncteur: {
      title: 'Power / circuit breaker issue',
      message: 'The power strip indicator is off. Check the circuit breaker in the electrical panel. If the breaker is OK, contact Support.',
    },
    sol_changer_pc: {
      title: 'Replace the integrated PC',
      message: 'The PC will not start despite checks. Replace the PC and contact Support for follow-up.',
    },
    sol_changer_ecran: {
      title: 'Replace the screen',
      message: 'The screen remains faulty after checks. Replace it and contact Support.',
    },
    sol_changer_pc_ecran: {
      title: 'Replace PC or screen',
      message: 'If possible, test with another screen to isolate the faulty component. Contact Support for replacement.',
    },
    sol_changer_alim: {
      title: 'Replace the power supply',
      message: 'The power supply is faulty. Replace it and contact Support.',
    },
    sol_changer_modem: {
      title: 'Replace the GSM modem',
      message: 'The modem will not connect despite checks. Replace it and contact Support.',
    },
    sol_antenne_ext: {
      title: 'Install an external antenna',
      message: 'The GSM signal is insufficient in this location. An external remote antenna is needed. Contact Support for installation.',
    },
    sol_changer_lecteur: {
      title: 'Replace the badge reader',
      message: 'The badge reader is faulty. Replace it and contact Support for reconfiguration.',
    },
    sol_badge_incompatible: {
      title: 'Incompatible badge',
      message: 'This badge type is not compatible with the EPIMAT reader. Order 125 kHz HID Kalistrut badges from Support.',
    },
    sol_badge_defaillant: {
      title: 'Defective badge — to replace',
      message: 'This specific badge is defective (other badges work). Replace the badge through Support.',
    },
    sol_redemarrer_pc: {
      title: 'Restart the PC',
      message: 'The EPIMAT software is not responding. Restart the PC (Start → Restart). If the problem persists after restart, contact Support.',
    },
    sol_sav_serveur: {
      title: 'Logimatiq server issue',
      message: 'The ClientSynch DB EPI test fails: the issue is with the Logimatiq server or SQL database. Contact Logimatiq Support for server intervention.',
    },
    tbd: {
      title: 'Tree to complete',
      message: 'This machine does not yet have a diagnostic tree. Contact Support directly.',
    },
  },
};
