/* ============================================================================
   ENGLISH TRANSLATIONS
   ui   → chaînes d'interface (clé = texte français)
   nodes → contenu des nœuds de l'arbre de diagnostic
   ========================================================================== */
export const EN = {

  /* ---- Chaînes d'interface ---- */
  ui: {
    // Splash
    'Démarrer un diagnostic': 'Start a diagnostic',
    'Diagnostic pas à pas': 'Step-by-step diagnostic',
    'Guide de diagnostic pas à pas pour techniciens et clients':
      'Step-by-step diagnostic guide for technicians and customers',
    'v0.2 · usage interne Logimatiq': 'v0.2 · Logimatiq internal use',

    // Login
    'Connexion': 'Login',
    'Identifiants fournis par Logimatiq': 'Credentials provided by Logimatiq',
    'Identifiant': 'Username',
    'Votre login': 'Your username',
    'Mot de passe': 'Password',
    'Votre mot de passe': 'Your password',
    '⚠ Identifiant ou mot de passe incorrect.': '⚠ Incorrect username or password.',
    'Se connecter →': 'Sign in →',
    'Contactez Logimatiq pour obtenir vos identifiants':
      'Contact Logimatiq to get your credentials',

    // Home
    'Connectez-vous': 'Sign in',
    'Chercher un symptôme, une fiche…': 'Search for a symptom, a guide…',
    'Démarrer un diagnostic': 'Start a diagnostic',
    'Bientôt disponible': 'Coming soon',
    'Guide de mise en service': 'Installation guide',
    'Checklist installation EPIMAT': 'EPIMAT installation checklist',
    'Récents': 'Recent',
    'Aucun diagnostic récent': 'No recent diagnostics',
    'Les diagnostics terminés apparaîtront ici':
      'Completed diagnostics will appear here',

    // Bottom nav
    'Accueil': 'Home',
    'Fiches': 'Guides',
    'Historique': 'History',

    // Symptoms
    'Quel est le problème ?': 'What is the problem?',
    'Affichage': 'Display',
    'Réseau': 'Network',
    'Badge': 'Badge',
    'Logiciel': 'Software',
    'Config': 'Config',

    // Machine select
    'Quelle machine ?': 'Which machine?',
    'Machines enregistrées': 'Registered machines',
    'Nouvelle machine': 'New machine',
    '← Retour à la liste': '← Back to list',
    'Numéro de série *': 'Serial number *',
    'Ex : EPM-2024-0042': 'E.g.: EPM-2024-0042',
    'Site / Emplacement': 'Site / Location',
    'Ex : Entrepôt Paris, Rayon 3…': 'E.g.: Paris Warehouse, Row 3…',
    'Client / Société': 'Customer / Company',
    'Nom du client final': 'End customer name',
    '⚠ Le numéro de série est obligatoire.': '⚠ Serial number is required.',
    'Enregistrer et continuer →': 'Save and continue →',

    // Diag UI
    'Étape': 'Step',
    'étapes': 'steps',
    'Procédure faite': 'Done',
    'Question': 'Question',
    'Procédure': 'Procedure',
    '← Retour': '← Back',
    "C'est fait ✓": 'Done ✓',
    'Quitter': 'Quit',
    'Quitter ce diagnostic ?': 'Quit this diagnostic?',
    'Se déconnecter ?': 'Sign out?',
    'Cheminement du diagnostic': 'Diagnostic path',
    'Copier le rapport': 'Copy report',
    '✓ Copié !': '✓ Copied!',
    'Contacter le SAV Logimatiq': 'Contact Logimatiq Support',
    'Refaire ce diagnostic': 'Redo this diagnostic',
    'Terminer': 'Done',
    'Nœud introuvable.': 'Node not found.',
    'SAV': 'Support',

    // Rapport
    '🔧 RAPPORT DIAGNOSTIC LOGIMATIQ': '🔧 LOGIMATIQ DIAGNOSTIC REPORT',
    'Machine  :': 'Machine  :',
    'Problème :': 'Problem  :',
    'Date     :': 'Date     :',
    'Généré par Logimatiq SAV App': 'Generated by Logimatiq Support App',
    'Rapport diagnostic Logimatiq': 'Logimatiq Diagnostic Report',

    // Outcome pills
    'Résolu': 'Resolved',
    'Pièce': 'Part',

    // History
    'Aucun diagnostic terminé': 'No completed diagnostics',
    'Les diagnostics complétés apparaîtront ici':
      'Completed diagnostics will appear here',
    'Total': 'Total',
    'Résolus': 'Resolved',
    'Taux': 'Rate',

    // Stats
    'Aucune donnée disponible': 'No data available',
    'Effectuez des diagnostics pour voir les statistiques':
      'Run diagnostics to see statistics',
    'Diagnostics': 'Diagnostics',
    'Machines': 'Machines',
    'Répartition des résultats': 'Result breakdown',
    'SAV requis': 'Support needed',
    'Pièce à changer': 'Part to replace',
    'Machines les plus actives': 'Most active machines',
    'Sociétés les plus actives': 'Most active companies',
    'Pannes les plus fréquentes': 'Most common faults',

    // Setup
    'Mise en service': 'Installation',
    'Base de connaissances': 'Knowledge base',
    'Progression': 'Progress',
    '✓ Complété': '✓ Completed',
    '✓ Installation complète !': '✓ Installation complete!',
    'La machine est prête à l\'utilisation.': 'The machine is ready to use.',
    'Réinitialiser la checklist': 'Reset checklist',
    'Réinitialiser toute la checklist d\'installation ?': 'Reset the entire installation checklist?',

    // Faults
    'Pannes': 'Faults',
    'Tambour, trappe, moteur…': 'Drum, hatch, motor…',
    'Pannes récurrentes': 'Recurring faults',
    'Rechercher une panne…': 'Search for a fault…',
    'Tout': 'All',
    'Symptômes': 'Symptoms',
    'Étapes de résolution': 'Resolution steps',
    'Photo à venir': 'Photo coming soon',
    'Appeler le SAV Logimatiq': 'Call Logimatiq Support',
    'Aucune panne trouvée': 'No fault found',
    'Essayez un autre mot-clé': 'Try another keyword',
    'Critique': 'Critical',
    'Urgent': 'Urgent',
    'Courant': 'Common',

    // KB
    'Fiches PDF': 'PDF Guides',
    'Codes erreur': 'Error codes',
    'écran noir, modem, badge…': 'black screen, modem, badge…',
    'ERR_SYNC, badge, réseau…': 'ERR_SYNC, badge, network…',
    'Aucun résultat pour': 'No results for',

    // User roles
    'Client': 'Customer',
    'Technicien revendeur': 'Reseller technician',
    'Technicien Logimatiq': 'Logimatiq technician',

    // Toolbar / headers statiques HTML
    'Statistiques': 'Statistics',
    'Se déconnecter': 'Sign out',
    'Logimatiq SAV': 'Logimatiq Support',
    'Tableau de bord': 'Dashboard',
    'EPIMAT': 'EPIMAT',
  },

  /* ---- Titres des symptômes (tree.js symptoms[]) ---- */
  symptoms: {
    't.epimat.screen':   'Black screen / no image / frozen screen',
    't.epimat.internet': 'No internet connection / modem offline',
    't.epimat.badge':    'Badge not read / not recognized / wrong number',
    't.log.demarrage':   "Software won't start / crashes",
    't.log.synchro':     'Software synchronization error',
    't.log.impression':  'Printing problem',
    't.log.config':      'Configuration / initial setup',
    't.vet.ph':          'To complete',
  },

  /* ---- Nœuds de l'arbre de diagnostic ---- */
  nodes: {

    /* === ARBRE ÉCRAN === */
    s_debut: {
      title: 'Is the machine plugged into the power outlet?',
      help: 'Check that the main power cable is properly connected to the power strip.',
      answers: ['Yes, plugged in', 'No, unplugged'],
    },
    s_brancher: {
      title: 'Connect the machine to the power outlet',
      steps: [
        'Check that the power strip is on (red indicator lit)',
        'Firmly connect the power cable on the machine side (supplied cable, exits at the bottom)',
        'Connect the other end to the power strip',
        'Wait 10 seconds',
      ],
    },
    s_led_ecran: {
      title: 'What is the color of the screen LED indicator?',
      help: 'Small indicator on the front of the monitor, at the bottom or side.',
      answers: ['Red', 'Off (no LED)', 'Green (image visible, other problem)'],
    },
    s_rouge_pc_led: {
      title: 'Is the PC LED on?',
      help: 'Light indicator on the front of the PC case built into the machine.',
      answers: ['Yes, PC LED on', 'No, PC off'],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    s_rouge_pc_ventilo: {
      title: 'Check the PC power supply',
      steps: [
        'Listen or look whether the PC fan is running',
        'Go to the back of the PC case',
        'Locate the ON/OFF switch near the PC power socket',
        'Switch it to OFF, wait 5 seconds, then switch it back to ON',
        'Return to the front and press the PC Power button',
        'Wait 15 seconds',
      ],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    s_rouge_pc_demarre: {
      title: 'Did the PC start? (LED on)',
      answers: ['Yes, LED on', 'No, still off'],
    },
    s_rouge_rebrancher_vga: {
      title: 'Disconnect and reconnect the VGA cable',
      help: "The screen's 3 cables (USB, power, VGA) all connect at the same place behind the screen.",
      steps: [
        'Locate the VGA cable (blue screw connector) between screen and PC',
        'Unplug the cable on the screen side, then on the PC side',
        'Firmly reconnect on both sides and tighten the thumbscrews',
        'Wait 10 seconds',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_rouge_vga_result: {
      title: 'Has the image returned on the screen?',
      answers: ['Yes, image OK', 'No, still red'],
    },
    s_rouge_changer_vga: {
      title: 'Replace the VGA cable',
      steps: [
        'Unplug the old VGA cable from both sides',
        'Connect a new VGA cable on the PC side, then on the screen side',
        'Tighten the thumbscrews',
        'Wait for the image to return (10 seconds)',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_rouge_apres_changer_vga: {
      title: 'Is the image now visible?',
      answers: ['Yes, image OK', 'No, screen red'],
    },
    s_eteint_machine: {
      title: 'Is the rest of the machine powered on?',
      help: 'PC LED, badge reader indicator, modem indicators.',
      answers: ['No, everything seems off', 'Yes, only the screen is off'],
    },
    s_eteint_cable: {
      title: 'Is the power cable properly connected on the screen side and on the power supply side?',
      help: 'It arrives behind the screen together with the USB and VGA cables.',
      answers: ['Yes, connected', 'No, disconnected'],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_eteint_brancher_cable: {
      title: 'Connect the screen power cable',
      steps: [
        'Firmly connect the end on the screen side',
        'Check the connection on the power supply side and on the power strip side',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_eteint_cable_result: {
      title: 'Does the screen turn on?',
      answers: ['Yes', 'No'],
    },
    s_eteint_multiprise: {
      title: 'Is the red LED on the power strip lit?',
      help: 'The power strip must show a red indicator to confirm it is powered.',
      answers: ['Yes, red LED lit', 'No, power strip off'],
    },
    s_eteint_changer_alim: {
      title: 'Replace the screen power supply',
      steps: [
        'Locate the screen power supply (black box on the cable)',
        'Unplug the faulty power supply',
        'Connect a new power supply of the same reference',
        'Turn the screen back on',
      ],
    },
    s_eteint_alim_result: {
      title: 'Did the screen turn on?',
      answers: ['Yes, screen on', 'No, still off'],
    },
    s_vert_symptome: {
      title: 'What is the problem?',
      answers: [
        'The touchscreen does not respond',
        'Damaged image: flickering, colors, broken screen',
        'DistEPI is not displayed (Windows desktop visible)',
        'Screen frozen / stuck',
        'Windows or BIOS error message',
      ],
    },
    s_vert_image: {
      title: 'What do you see on the screen?',
      answers: [
        'Flickering or abnormal colors',
        'Wrong resolution (image too large or cut off)',
        'Broken or cracked screen',
      ],
    },
    s_vert_vga: {
      title: 'Check the VGA cable',
      steps: [
        'Locate the VGA cable (blue connector) between screen and PC',
        'Unplug and firmly reconnect on both sides',
        'Tighten the thumbscrews',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_vert_vga_result: {
      title: 'Has the image problem disappeared?',
      answers: ['Yes, stable image', 'No, problem persists'],
    },
    s_vert_usb: {
      title: 'Check the USB cable between screen and PC',
      steps: [
        'Locate the USB cable connecting the screen to the PC (needed for touch)',
        'Unplug and firmly reconnect on both sides',
        'If possible, try another USB port on the PC',
      ],
      media: 'Behind the screen (17-inch kit): USB, power and VGA cable connections',
    },
    s_vert_usb_result: {
      title: 'Is the touchscreen responding now?',
      answers: ['Yes, touch OK', 'No, still inactive'],
    },
    s_vert_distepi: {
      title: 'Launch the DistEPI software',
      steps: [
        'On the Windows desktop, double-click the DistEPI icon',
        'If the icon is missing: run C:\\EPI\\DistEPI.exe',
        'Wait for full loading (about 30 seconds)',
      ],
    },
    s_vert_distepi_result: {
      title: 'Did DistEPI launch correctly?',
      answers: ['Yes, DistEPI launched', "No, won't open"],
    },
    s_vert_resolution: {
      title: 'Fix the resolution (1280 × 720)',
      steps: [
        'Right-click on the Windows desktop',
        'Click "Display settings"',
        'Under Resolution, select 1280 × 720',
        'Click "Keep changes"',
      ],
    },
    s_vert_resolution_result: {
      title: 'Is the resolution correct now?',
      answers: ['Yes, display correct', 'No, still incorrect'],
    },
    s_redemarrer_distrib: {
      title: 'Restart the dispenser',
      steps: [
        'Start → Shut down → Restart',
        'If the screen is frozen: hold the PC Power button for 5 seconds, then turn it back on',
        'Wait for Windows and DistEPI to fully start',
      ],
    },
    s_redemarrer_distrib_result: {
      title: 'After the restart, is DistEPI displayed correctly?',
      answers: ['Yes', 'No'],
    },
    s_vert_redemarrer: {
      title: 'Restart the machine',
      steps: [
        'Click Start → Shut down → Restart',
        'If screen is frozen: hold the Power button for 5 seconds to force shutdown',
        'Turn back on with the Power button',
        'Wait for Windows to fully restart',
        'Check that DistEPI restarts automatically',
      ],
    },
    s_vert_redemarrer_result: {
      title: 'Is the machine working correctly after restart?',
      answers: ['Yes, everything OK', 'No, problem persists'],
    },
    s_vert_erreur: {
      title: 'Note the message, then restart the dispenser',
      steps: [
        'Photograph or write down the error message',
        'Start → Shut down → Restart (or hold the Power button for 5 seconds)',
        'Wait for the full startup',
      ],
    },
    s_vert_erreur_result: {
      title: 'Has the error message disappeared?',
      answers: ['Yes', 'No, it comes back'],
    },

    /* === ARBRE INTERNET === */
    i_debut: {
      title: 'What is the problem?',
      help: 'Four-Faith modem indicators: steady blue Online = internet OK; blinking ETH = link with the PC OK.',
      answers: [
        '"Online" LED off',
        '"Online" LED on but DistEPI sync error',
        'Frequent disconnections / unstable signal',
      ],
      media: [
        'Location of the modem in the machine (circled in red)',
        'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
      ],
    },
    i_pwr_led: {
      title: "Is the modem's PWR LED on (steady blue)?",
      answers: ['Yes', 'No, modem off'],
      media: 'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
    },
    i_alim_modem: {
      title: "Check the modem's power supply",
      steps: [
        'Check that the power jack is fully inserted into the modem',
        'Check that its power adapter is plugged in and powered',
        'Wait 2 to 3 minutes',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_alim_modem_result: {
      title: 'Does the PWR LED turn on?',
      answers: ['Yes', 'No'],
    },
    i_reboot_modem: {
      title: 'Restart the modem',
      steps: [
        "Unplug the modem's power supply (jack), or switch it OFF if it has a switch",
        'Wait 30 seconds',
        'Plug the power supply back in',
        'Wait 2 to 3 minutes for the modem to reconnect to the mobile network',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_reboot_result: {
      title: 'Is the "Online" LED now on?',
      answers: ['Yes, blue LED on', 'No, still off'],
    },
    i_antennes_check: {
      title: 'Check the 2 modem antennas',
      steps: [
        'Check that both antennas are properly screwed onto the modem',
        'If an antenna is loose, screw it back firmly',
        'Wait 1 minute and observe the Online LED',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_antennes_result: {
      title: 'Did the "Online" LED turn on?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    i_sim_led: {
      title: 'Is the modem SIM LED on?',
      help: 'Blue SIM LED = SIM card detected.',
      answers: ['Yes, SIM LED on', 'No, SIM LED off'],
      media: 'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
    },
    i_reinsertion_sim: {
      title: 'Re-insert the SIM card',
      steps: [
        "Cut the modem's power supply",
        'Eject the SIM with a pen or a pointed tool (ejection hole)',
        'Clean the gold contacts with a dry cloth',
        'Re-insert the SIM the right way round, then turn the modem back on',
        'Wait 2 to 3 minutes',
      ],
      media: 'Eject the SIM with a pointed tool in the ejection hole',
    },
    i_sim_result: {
      title: 'Is the SIM LED now on?',
      answers: ['Yes, SIM LED on', 'No, still off'],
    },
    i_setup_grizzly: {
      title: 'Run the router configuration again (Logimatiq program)',
      steps: [
        'Run setup_config_routeur_four_faith_1.0.0.17.exe (C:\\EPI folder)',
        'User Account Control: "Oui" (Yes), then "Suivant" (Next), "Suivant", "Installer" (Install)',
        '"La connexion à Internet est-elle fournie par un routeur installé par Logimatiq ?" (internet provided by a Logimatiq router?): "Oui" (Yes)',
        'Choose the SIM card APN from the list (wbdata, matooma.m2m, orange…), then "Enregistrer les paramètres et Fermer" (Save settings and Close)',
        '"Configuration terminée avec succès" (configuration completed): OK, then "Non, je préfère redémarrer plus tard" (restart later) and "Terminer" (Finish)',
        'Wait 2 to 3 minutes and observe the Online LED',
      ],
      media: [
        'Question "La connexion à Internet est-elle fournie par un routeur installé par Logimatiq ?": answer "Oui" (Yes)',
        'Choose the SIM card APN from the list',
      ],
    },
    i_setup_result: {
      title: 'Is the "Online" LED now on?',
      answers: ['Yes, blue LED on', 'No, still off'],
    },
    i_eth_led: {
      title: "Is the modem's ETH LED blinking?",
      help: "Blinking ETH = the modem is exchanging data with the machine's PC.",
      answers: ['Yes, it is blinking', 'No, off or steady'],
      media: 'Modem indicators: ETH, Online, signal, SIM, SYS, PWR',
    },
    i_connexion_distante: {
      title: "Can we connect remotely to the machine's PC?",
      help: 'If remote connection works, the RJ45 cable is not the cause.',
      answers: ['Yes, remote connection OK', 'No, no remote connection'],
    },
    i_test_url: {
      title: 'Test access to the EPIMAT server from the PC',
      steps: [
        "On the machine's PC, open Internet Explorer",
        'Go to https://epimat.logimatiq.com',
        'Check that the page opens without a certificate warning',
      ],
    },
    i_test_url_result: {
      title: 'Does the page open normally?',
      help: 'If Internet Explorer can reach the EPIMAT address, the EPIMAT applications work (network prerequisites).',
      answers: ['Yes', 'No'],
    },
    i_rj45_check: {
      title: 'Check the RJ45 cable (PC ↔ modem)',
      steps: [
        "Locate the RJ45 cable connecting the PC to the modem's ETH port",
        'Unplug and reconnect firmly on both ends until it clicks',
        'Check that the Windows PC shows an internet connection',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_rj45_result: {
      title: 'Does the Windows PC now have internet access?',
      answers: ['Yes, internet OK', 'No, still no network'],
    },
    i_clientsynch: {
      title: 'Test with ClientSynch DB EPI (Grizzly)',
      steps: [
        'On the Windows desktop, open the ClientSynch DB EPI software',
        'Run the data receive and send test',
        'Observe whether the test passes or fails',
      ],
      media: 'ClientSynch DB EPI — procedure (photos coming soon)',
    },
    i_clientsynch_result: {
      title: 'Did the ClientSynch test succeed?',
      answers: ['Yes, test OK', 'No, test fails'],
    },
    i_reboot_pc_distepi: {
      title: 'Restart the PC',
      steps: [
        'Click Start → Shut down → Restart',
        'Wait for Windows to fully restart',
        'Check that DistEPI restarts and sync works',
      ],
    },
    i_reboot_distepi_result: {
      title: 'Is DistEPI working correctly after the restart?',
      answers: ['Yes, sync OK', 'No, error persists'],
    },
    i_signal_faible: {
      title: 'Check antennas and reposition the modem',
      help: 'Signal LEDs (bars in the middle of the modem): the more bars, the better the signal.',
      steps: [
        'Check that both antennas are properly screwed onto the modem',
        'Straighten the antennas vertically',
        'If possible, move the modem closer to a window',
        'Use a mobile phone to check the signal strength in the room',
      ],
      media: 'Modem connectors: 2 antennas, power (PWR) and the RJ45 cable from the PC on ETH',
    },
    i_signal_result: {
      title: 'Is the connection stable now?',
      answers: ['Yes, stable connection', 'No, still unstable'],
    },

    /* === ARBRE BADGE === */
    b_debut: {
      title: 'Is the badge reader LED on?',
      help: 'The reader is connected to the PC via USB: if its LED is off, the PC is probably off.',
      answers: ['Yes, LED on', 'No, LED off'],
      media: 'The badge reader (circled in red)',
    },
    b_pc_led: {
      title: 'Is the PC LED on?',
      answers: ['No, PC off', 'Yes, PC on'],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    b_allumer_pc: {
      title: 'Turn on the PC',
      steps: [
        'Press the Power button on the front of the PC case',
        'If nothing happens, set the ON/OFF switch at the back to ON',
        'Press the Power button again',
        'Wait 15 seconds',
      ],
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    b_led_apres_pc: {
      title: 'Is the reader LED now on?',
      answers: ['Yes', 'No'],
    },
    b_usb_rebranch: {
      title: 'Disconnect and reconnect the reader USB cable',
      steps: [
        'Unplug the USB cable from the reader on the PC side',
        'Wait 5 seconds',
        'Firmly reconnect to the same USB port',
        'Observe if the reader LED turns on',
      ],
    },
    b_led_apres_usb: {
      title: 'Is the reader LED now on?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_autre_port_usb: {
      title: 'Try another USB port',
      steps: [
        'Unplug the reader USB cable',
        'Plug it into another USB port on the PC',
        'Observe if the reader LED turns on',
      ],
    },
    b_led_autre_port: {
      title: 'Did the LED turn on on the new port?',
      answers: ['Yes, LED on', 'No, still off'],
    },
    b_symptome: {
      title: 'What happens when the badge is presented?',
      help: 'The reader beeps when it reads a badge.',
      answers: [
        'Nothing: no beep, no reaction',
        'Beep, but nothing happens on the screen',
        'The screen asks "INITIALISATION BADGE — Tapez votre code !" (enter your code)',
        'Badge read but refused, wrong name or wrong number',
        'Random / intermittent reading',
      ],
    },
    b_autre_badge: {
      title: 'Test with another badge',
      steps: [
        "Take a badge that works (maintenance badge or a colleague's badge)",
        'Present it in front of the reader',
        'Listen for the beep and watch the screen',
      ],
    },
    b_autre_badge_result: {
      title: 'Is the other badge read?',
      answers: ['Yes, the other badge is read', 'No, no badge is read'],
    },
    b_badge_deja_ok: {
      title: 'Has the first badge ever worked on this machine?',
      answers: ['Yes, it used to work', 'No, it is a new type of badge'],
    },
    b_notepad_langue: {
      title: 'Prepare Notepad test — switch keyboard to English',
      help: 'The USB reader works like a keyboard: it "types" the badge number.',
      steps: [
        'Click on the language at the bottom right of the Windows taskbar',
        'Select "ENG" (English) as the input language',
        'Open Notepad: Start → Notepad',
        'Click in the Notepad text area',
      ],
    },
    b_notepad_test: {
      title: 'Test badge reading on Notepad',
      steps: [
        'In Notepad (English keyboard), swipe the badge in front of the reader',
        'Observe what appears in the text area',
      ],
    },
    b_notepad_result: {
      title: 'What appears in Notepad?',
      answers: ['Characters appear (e.g.: 3A8F12B4)', 'Nothing appears'],
    },
    b_admin_base: {
      title: 'Fix the character count in Admin Base',
      steps: [
        'In DistEPI, go to "Admin Base"',
        'Find the badge character count parameter',
        'Count the number of characters read in Notepad',
        'Correct the parameter to match',
        'Save and restart DistEPI',
      ],
      media: 'Admin Base — character count parameter (photos coming soon)',
    },
    b_admin_result: {
      title: 'Is the badge now recognized in DistEPI?',
      answers: ['Yes, badge OK', 'No, still ignored'],
    },
    b_reprogrammer: {
      title: 'Reprogram the badge reader',
      steps: [
        'Open the reader programming software',
        'Follow the reprogramming procedure',
        'Re-test with Notepad after reprogramming',
      ],
      media: 'Reader reprogramming procedure (tutorial coming soon)',
    },
    b_reprogrammer_result: {
      title: 'Does the reader read correctly in Notepad?',
      answers: ['Yes, characters visible', 'No, still nothing'],
    },
    b_bip_redemarrer: {
      title: 'Restart the dispenser',
      steps: [
        'Start → Shut down → Restart',
        'Wait for Windows and DistEPI to fully start',
        'Present the badge again',
      ],
    },
    b_bip_result: {
      title: 'Does the badge work after the restart?',
      answers: ['Yes', 'No'],
    },
    b_init_badge: {
      title: 'Initialize the badge (first use on this machine)',
      steps: [
        'Enter the number printed on the badge, adding leading zeros to get 7 digits',
        'Examples: badge 529545 → 0529545; badge 14 → 0000014',
        'Check the name displayed, then confirm with OK',
      ],
      media: '"INITIALISATION BADGE" screen: enter the badge number as 7 digits',
    },
    b_init_result: {
      title: 'Is the correct name displayed?',
      answers: ['Yes', 'No, wrong or unknown name'],
    },
    b_salarie_extranet: {
      title: 'Check the employee in the EPIMAT extranet',
      steps: [
        'Log in to https://epimat.logimatiq.com/client',
        '"Salariés" (Employees) → search for the employee',
        'Check the badge number (7 digits), the profile and access to this machine',
        'Correct and save',
        'On the machine, run a synchronization: keyboard plugged into the PC, Shift + L (maintenance menu), then the "Synchroniser" (Synchronize) button',
      ],
    },
    b_salarie_result: {
      title: 'Is the badge recognized now?',
      answers: ['Yes', 'No'],
    },
    b_sync: {
      title: 'Run a synchronization and check the 4G connection',
      steps: [
        "Check that the modem's Online LED is steady blue (otherwise: Internet / modem tree)",
        "Plug a keyboard into the machine's PC",
        'Shift + L to open the maintenance menu, then click the "Synchroniser" (Synchronize) button',
        'Wait for the synchronization to finish, then present the badge again',
      ],
    },
    b_sync_result: {
      title: 'Is the badge recognized now?',
      answers: ['Yes', 'No'],
    },
    b_mauvais_notepad: {
      title: 'Check the read number — Notepad test (English keyboard)',
      steps: [
        'Switch Windows keyboard to English (taskbar → ENG)',
        'Open Notepad and swipe the badge in front of the reader',
        'Compare the number displayed with the one printed on the badge',
      ],
    },
    b_mauvais_result: {
      title: 'Does the number read in Notepad match the badge?',
      answers: [
        'Yes, same number — incorrectly entered in the database',
        'No, different number — reader to reprogram',
      ],
    },
    b_corriger_bdd: {
      title: "Correct the employee's badge number",
      steps: [
        'EPIMAT extranet → "Salariés" (Employees) → employee record → "Modifier" (Edit)',
        'Correct the badge number with the exact number of the physical badge',
        'Save',
        'On the machine: Shift + L (maintenance menu), "Synchroniser" (Synchronize) button, then test the badge again',
      ],
    },
    b_bdd_result: {
      title: 'Is the badge now correctly recognized?',
      answers: ['Yes', 'No'],
    },
    b_alea_badge: {
      title: 'Test with another badge',
      steps: [
        'Take another available badge',
        'Swipe it in front of the reader',
        'Observe whether the reading is stable with this other badge',
      ],
    },
    b_alea_badge_result: {
      title: 'Does the other badge work correctly?',
      answers: ['Yes, stable reading', 'No, same problem', 'No other badge available'],
    },
    b_alea_usb: {
      title: 'Check the reader USB cable',
      steps: [
        'Unplug the reader USB cable',
        'Inspect the cable (bends, visible damage)',
        'Firmly reconnect or replace the cable if damaged',
        'Test reading with several badges',
      ],
    },
    b_alea_usb_result: {
      title: 'Is the reading stable now?',
      answers: ['Yes, stable reading', 'No, still random'],
    },

    /* === SOLUTIONS === */
    sol_resolved: {
      title: 'Problem resolved',
      message: 'The machine is working correctly again. Remember to close the support ticket if applicable.',
    },
    sol_sav: {
      title: 'Contact Support',
      message: 'The problem persists after the checks. Contact Logimatiq Support and send them the diagnostic report.',
    },
    sol_disjoncteur: {
      title: 'Power / circuit breaker issue',
      message: 'The machine or the power strip is not powered. Check the connections and the circuit breaker in the electrical panel of the room. If the breaker is OK, contact Support.',
    },
    sol_changer_pc: {
      title: 'Replace the integrated PC',
      message: 'The PC no longer starts despite the checks. Replace the PC, check that everything works with DEBES, and contact Support.',
      media: 'The PC is in the bottom compartment of the machine (circled in red)',
    },
    sol_changer_ecran: {
      title: 'Replace the screen',
      message: 'The screen remains faulty after the checks. Replace it (remove the protective plate, disconnect, unscrew) and contact Support.',
    },
    sol_changer_pc_ecran: {
      title: 'Replace PC or screen',
      message: 'If possible, test with another screen to isolate the faulty component. Contact Support for replacement.',
    },
    sol_changer_alim: {
      title: "Replace the screen's power supply unit",
      message: 'The screen turns back on with a new power supply: the old unit was faulty. Report the replaced part to Support.',
    },
    sol_changer_modem: {
      title: 'Replace the GSM modem',
      message: 'The modem no longer connects despite the checks. Replace it (keep the SIM, disconnect the power supply and the antennas) and contact Support.',
    },
    sol_antenne_ext: {
      title: 'Install an external antenna',
      message: 'The GSM signal is insufficient in this location. An external remote antenna is needed. Contact Support for installation.',
    },
    sol_sav_serveur: {
      title: 'Logimatiq server issue',
      message: 'The ClientSynch DB EPI test fails: the issue is with the Logimatiq server or the SQL database. Contact Logimatiq Support.',
    },
    sol_changer_lecteur: {
      title: 'Replace the badge reader',
      message: 'The badge reader is faulty. Replace it (move the connector over to the new reader), check that it beeps when a badge is presented, and contact Support.',
      media: 'The badge reader seen from inside the door (circled in orange)',
    },
    sol_badge_incompatible: {
      title: 'Incompatible badge: reprogram the reader',
      message: 'The reader is not programmed for this type of badge (MIFARE…). The badge reader must be reprogrammed so that it can read it: contact Support.',
    },
    sol_badge_defaillant: {
      title: 'Defective badge — to replace',
      message: 'This specific badge is defective (other badges work). Replace the badge through Support.',
    },
    tbd: {
      title: 'Tree to complete',
      message: 'This machine does not yet have a diagnostic tree. Contact Support directly.',
    },
  },
};
